graph TD
    BB_3["BB3\n"]
    BB_1["BB1\nt1 = 1\nt2 = 1\nt3 = (t1 == t2)\nif t3 goto BB_2 else BB_3"]
    BB_4["BB4\nreturn i"]
    BB_5["BB5\ngoto BB_6"]
    BB_2["BB2\nt4 = pool\[?\]\nt5 = t4\[i\] (str)\nc = t5\nt7 = 32\nt8 = (c == t7)\nif t8 goto BB_4 else BB_5"]
    BB_7["BB7\nt14 = 1\nt15 = -t14\nreturn t15"]
    BB_8["BB8\ngoto BB_9"]
    BB_6["BB6\nt9 = 0\nt10 = (c == t9)\nt11 = 10\nt12 = (c == t11)\nt13 = t10 || t12\nif t13 goto BB_7 else BB_8"]
    BB_9["BB9\nt16 = 1\nt17 = i + t16\ni = t17\ngoto BB_1"]
    BB_0["BB0\ni = start\ngoto BB_1"]
BB_1 --> BB_2
BB_1 --> BB_3
BB_4 --> BB_6
BB_5 --> BB_6
BB_2 --> BB_4
BB_2 --> BB_5
BB_7 --> BB_9
BB_8 --> BB_9
BB_6 --> BB_7
BB_6 --> BB_8
BB_9 --> BB_1
BB_0 --> BB_1
