graph TD;
N0["function: map_update"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["field_access .val"]
N5 --> N6
N7["expr"]
N6 --> N7
N8["identifier: entries"]
N7 --> N8
N9["="]
N4 --> N9
N10["expr"]
N4 --> N10
N11["identifier: pool_next"]
N10 --> N11
N12[";"]
N2 --> N12
N13["statement"]
N0 --> N13
N14["expression_statement"]
N13 --> N14
N15["expr"]
N14 --> N15
N16["binary_expr"]
N15 --> N16
N17["expr"]
N16 --> N17
N18["identifier: pool_next"]
N17 --> N18
N19["="]
N16 --> N19
N20["expr"]
N16 --> N20
N21["call_expr"]
N20 --> N21
N22["expr"]
N21 --> N22
N23["identifier: strcpy_at"]
N22 --> N23
N24["expr"]
N21 --> N24
N25["identifier: pool_next"]
N24 --> N25
N26["expr"]
N21 --> N26
N27["identifier: val_off"]
N26 --> N27
N28[";"]
N14 --> N28
