graph TD;
N0["function: map_find"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: i"]
N5 --> N6
N7["="]
N4 --> N7
N8["expr"]
N4 --> N8
N9["literal"]
N8 --> N9
N10["dec: 0"]
N9 --> N10
N11[";"]
N2 --> N11
N12["statement"]
N0 --> N12
N13["loop_statement"]
N12 --> N13
N14["while"]
N13 --> N14
N15["expr"]
N13 --> N15
N16["binary_expr"]
N15 --> N16
N17["expr"]
N16 --> N17
N18["identifier: i"]
N17 --> N18
N19["<"]
N16 --> N19
N20["expr"]
N16 --> N20
N21["identifier: map_n"]
N20 --> N21
N22["statement"]
N13 --> N22
N23["if_statement"]
N22 --> N23
N24["if"]
N23 --> N24
N25["expr"]
N23 --> N25
N26["binary_expr"]
N25 --> N26
N27["expr"]
N26 --> N27
N28["call_expr"]
N27 --> N28
N29["expr"]
N28 --> N29
N30["identifier: streq"]
N29 --> N30
N31["expr"]
N28 --> N31
N32["field_access .key"]
N31 --> N32
N33["expr"]
N32 --> N33
N34["slice_expr"]
N33 --> N34
N35["expr"]
N34 --> N35
N36["identifier: entries"]
N35 --> N36
N37["range"]
N34 --> N37
N38["expr"]
N37 --> N38
N39["identifier: i"]
N38 --> N39
N40["expr"]
N28 --> N40
N41["identifier: key_off"]
N40 --> N41
N42["=="]
N26 --> N42
N43["expr"]
N26 --> N43
N44["literal"]
N43 --> N44
N45["dec: 1"]
N44 --> N45
N46["statement"]
N23 --> N46
N47["block_statement"]
N46 --> N47
N48["begin"]
N47 --> N48
N49["statement"]
N47 --> N49
N50["return_statement"]
N49 --> N50
N51["expr"]
N50 --> N51
N52["identifier: i"]
N51 --> N52
N53["end"]
N47 --> N53
N54["statement"]
N13 --> N54
N55["expression_statement"]
N54 --> N55
N56["expr"]
N55 --> N56
N57["binary_expr"]
N56 --> N57
N58["expr"]
N57 --> N58
N59["identifier: i"]
N58 --> N59
N60["="]
N57 --> N60
N61["expr"]
N57 --> N61
N62["binary_expr"]
N61 --> N62
N63["expr"]
N62 --> N63
N64["identifier: i"]
N63 --> N64
N65["+"]
N62 --> N65
N66["expr"]
N62 --> N66
N67["literal"]
N66 --> N67
N68["dec: 1"]
N67 --> N68
N69[";"]
N55 --> N69
N70["end"]
N13 --> N70
N71["statement"]
N0 --> N71
N72["return_statement"]
N71 --> N72
N73["expr"]
N72 --> N73
N74["unary_expr"]
N73 --> N74
N75["-"]
N74 --> N75
N76["expr"]
N74 --> N76
N77["literal"]
N76 --> N77
N78["dec: 1"]
N77 --> N78
