graph TD
    BB_3["BB3\nt164 = pool\[?\]\nt165 = t164\[di\] (str)\nt166 = 0\nt168 = pool\[?\]\nt168\[di\] = t166 (str)\nreturn"]
    BB_1["BB1\nt146 = map_n\[?\]\nt147 = (i < t146)\nif t147 goto BB_2 else BB_3"]
    BB_4["BB4\nt150 = pool\[?\]\nt151 = t150\[di\] (str)\nt152 = 44\nt154 = pool\[?\]\nt154\[di\] = t152 (str)\nt155 = 1\nt156 = di + t155\ndi = t156\ngoto BB_6"]
    BB_5["BB5\ngoto BB_6"]
    BB_2["BB2\nt148 = 0\nt149 = (i > t148)\nif t149 goto BB_4 else BB_5"]
    BB_6["BB6\nt158 = entries\[0\]\nt159 = strcpy_at(di, t158)\ndi = t159\nt161 = 1\nt162 = i + t161\ni = t162\ngoto BB_1"]
    BB_0["BB0\nt142 = 256\ndi = t142\nt144 = 0\ni = t144\ngoto BB_1"]
BB_1 --> BB_2
BB_1 --> BB_3
BB_4 --> BB_6
BB_5 --> BB_6
BB_2 --> BB_4
BB_2 --> BB_5
BB_6 --> BB_1
BB_0 --> BB_1
