graph TD
    BB_9["BB9\nreturn"]
    BB_1["BB1\nreturn"]
    BB_2["BB2\ngoto BB_3"]
    BB_0["BB0\nt169 = r0\[?\]\nt170 = 0\nr0 = t170\nt172 = r1\[?\]\nt173 = 1\nt174 = -t173\nr1 = t174\nt176 = r2\[?\]\nt177 = 1\nt178 = -t177\nr2 = t178\nt180 = 0\nt181 = find_space(t180)\nsp1 = t181\nt183 = 1\nt184 = -t183\nt185 = (sp1 == t184)\nif t185 goto BB_1 else BB_2"]
    BB_4["BB4\nreturn"]
    BB_5["BB5\ngoto BB_6"]
    BB_3["BB3\nt186 = pool\[?\]\nt187 = t186\[sp1\] (str)\nt188 = 0\nt190 = pool\[?\]\nt190\[sp1\] = t188 (str)\nt191 = r1\[?\]\nt192 = 1\nt193 = sp1 + t192\nr1 = t193\nt195 = r1\[?\]\nt196 = find_space(t195)\nsp2 = t196\nt198 = 1\nt199 = -t198\nt200 = (sp2 == t199)\nif t200 goto BB_4 else BB_5"]
    BB_7["BB7\nt212 = 1\nt213 = 1\nt214 = (t212 == t213)\nif t214 goto BB_8 else BB_9"]
    BB_10["BB10\nreturn"]
    BB_11["BB11\ngoto BB_12"]
    BB_8["BB8\nt215 = pool\[?\]\nt216 = r2\[?\]\nt217 = t216 + nl\nt218 = t215\[t217\] (str)\nc = t218\nt220 = 0\nt221 = (c == t220)\nif t221 goto BB_10 else BB_11"]
    BB_13["BB13\nt224 = pool\[?\]\nt225 = r2\[?\]\nt226 = t225 + nl\nt227 = t224\[t226\] (str)\nt228 = 0\nt230 = r2\[?\]\nt231 = t230 + nl\nt232 = pool\[?\]\nt232\[t231\] = t228 (str)\nreturn"]
    BB_14["BB14\ngoto BB_15"]
    BB_12["BB12\nt222 = 10\nt223 = (c == t222)\nif t223 goto BB_13 else BB_14"]
    BB_15["BB15\nt233 = 1\nt234 = nl + t233\nnl = t234\ngoto BB_7"]
    BB_6["BB6\nt201 = pool\[?\]\nt202 = t201\[sp2\] (str)\nt203 = 0\nt205 = pool\[?\]\nt205\[sp2\] = t203 (str)\nt206 = r2\[?\]\nt207 = 1\nt208 = sp2 + t207\nr2 = t208\nt210 = 0\nnl = t210\ngoto BB_7"]
BB_1 --> BB_3
BB_2 --> BB_3
BB_0 --> BB_1
BB_0 --> BB_2
BB_4 --> BB_6
BB_5 --> BB_6
BB_3 --> BB_4
BB_3 --> BB_5
BB_7 --> BB_8
BB_7 --> BB_9
BB_10 --> BB_12
BB_11 --> BB_12
BB_8 --> BB_10
BB_8 --> BB_11
BB_13 --> BB_15
BB_14 --> BB_15
BB_12 --> BB_13
BB_12 --> BB_14
BB_15 --> BB_7
BB_6 --> BB_7
