graph TD
    BB_3["BB3\nreturn"]
    BB_1["BB1\nt65 = 1\nt66 = 1\nt67 = (t65 == t66)\nif t67 goto BB_2 else BB_3"]
    BB_4["BB4\nreturn"]
    BB_5["BB5\ngoto BB_6"]
    BB_2["BB2\nt68 = pool\[?\]\nt69 = off + i\nt70 = t68\[t69\] (str)\nc = t70\nt72 = 0\nt73 = (c == t72)\nif t73 goto BB_4 else BB_5"]
    BB_6["BB6\nt74 = putchar(c)\nt75 = 1\nt76 = i + t75\ni = t76\ngoto BB_1"]
    BB_0["BB0\nt63 = 0\ni = t63\ngoto BB_1"]
BB_1 --> BB_2
BB_1 --> BB_3
BB_4 --> BB_6
BB_5 --> BB_6
BB_2 --> BB_4
BB_2 --> BB_5
BB_6 --> BB_1
BB_0 --> BB_1
