graph TD;
N0["function: respond_err"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["call_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: putchar"]
N5 --> N6
N7["expr"]
N4 --> N7
N8["literal"]
N7 --> N8
N9["dec: 69"]
N8 --> N9
N10[";"]
N2 --> N10
N11["statement"]
N0 --> N11
N12["expression_statement"]
N11 --> N12
N13["expr"]
N12 --> N13
N14["call_expr"]
N13 --> N14
N15["expr"]
N14 --> N15
N16["identifier: putchar"]
N15 --> N16
N17["expr"]
N14 --> N17
N18["literal"]
N17 --> N18
N19["dec: 82"]
N18 --> N19
N20[";"]
N12 --> N20
N21["statement"]
N0 --> N21
N22["expression_statement"]
N21 --> N22
N23["expr"]
N22 --> N23
N24["call_expr"]
N23 --> N24
N25["expr"]
N24 --> N25
N26["identifier: putchar"]
N25 --> N26
N27["expr"]
N24 --> N27
N28["literal"]
N27 --> N28
N29["dec: 82"]
N28 --> N29
N30[";"]
N22 --> N30
N31["statement"]
N0 --> N31
N32["expression_statement"]
N31 --> N32
N33["expr"]
N32 --> N33
N34["call_expr"]
N33 --> N34
N35["expr"]
N34 --> N35
N36["identifier: putchar"]
N35 --> N36
N37["expr"]
N34 --> N37
N38["literal"]
N37 --> N38
N39["dec: 32"]
N38 --> N39
N40[";"]
N32 --> N40
N41["statement"]
N0 --> N41
N42["expression_statement"]
N41 --> N42
N43["expr"]
N42 --> N43
N44["call_expr"]
N43 --> N44
N45["expr"]
N44 --> N45
N46["identifier: putstr_at"]
N45 --> N46
N47["expr"]
N44 --> N47
N48["identifier: off"]
N47 --> N48
N49[";"]
N42 --> N49
N50["statement"]
N0 --> N50
N51["expression_statement"]
N50 --> N51
N52["expr"]
N51 --> N52
N53["call_expr"]
N52 --> N53
N54["expr"]
N53 --> N54
N55["identifier: putchar"]
N54 --> N55
N56["expr"]
N53 --> N56
N57["literal"]
N56 --> N57
N58["dec: 10"]
N57 --> N58
N59[";"]
N51 --> N59
