graph TD;
N0["function: streq"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: i"]
N5 --> N6
N7["="]
N4 --> N7
N8["expr"]
N4 --> N8
N9["literal"]
N8 --> N9
N10["dec: 0"]
N9 --> N10
N11[";"]
N2 --> N11
N12["statement"]
N0 --> N12
N13["loop_statement"]
N12 --> N13
N14["while"]
N13 --> N14
N15["expr"]
N13 --> N15
N16["binary_expr"]
N15 --> N16
N17["expr"]
N16 --> N17
N18["literal"]
N17 --> N18
N19["dec: 1"]
N18 --> N19
N20["=="]
N16 --> N20
N21["expr"]
N16 --> N21
N22["literal"]
N21 --> N22
N23["dec: 1"]
N22 --> N23
N24["statement"]
N13 --> N24
N25["expression_statement"]
N24 --> N25
N26["expr"]
N25 --> N26
N27["binary_expr"]
N26 --> N27
N28["expr"]
N27 --> N28
N29["identifier: ca"]
N28 --> N29
N30["="]
N27 --> N30
N31["expr"]
N27 --> N31
N32["slice_expr"]
N31 --> N32
N33["expr"]
N32 --> N33
N34["identifier: pool"]
N33 --> N34
N35["range"]
N32 --> N35
N36["expr"]
N35 --> N36
N37["binary_expr"]
N36 --> N37
N38["expr"]
N37 --> N38
N39["identifier: a"]
N38 --> N39
N40["+"]
N37 --> N40
N41["expr"]
N37 --> N41
N42["identifier: i"]
N41 --> N42
N43[";"]
N25 --> N43
N44["statement"]
N13 --> N44
N45["expression_statement"]
N44 --> N45
N46["expr"]
N45 --> N46
N47["binary_expr"]
N46 --> N47
N48["expr"]
N47 --> N48
N49["identifier: cb"]
N48 --> N49
N50["="]
N47 --> N50
N51["expr"]
N47 --> N51
N52["slice_expr"]
N51 --> N52
N53["expr"]
N52 --> N53
N54["identifier: pool"]
N53 --> N54
N55["range"]
N52 --> N55
N56["expr"]
N55 --> N56
N57["binary_expr"]
N56 --> N57
N58["expr"]
N57 --> N58
N59["identifier: b"]
N58 --> N59
N60["+"]
N57 --> N60
N61["expr"]
N57 --> N61
N62["identifier: i"]
N61 --> N62
N63[";"]
N45 --> N63
N64["statement"]
N13 --> N64
N65["if_statement"]
N64 --> N65
N66["if"]
N65 --> N66
N67["expr"]
N65 --> N67
N68["binary_expr"]
N67 --> N68
N69["expr"]
N68 --> N69
N70["identifier: ca"]
N69 --> N70
N71["!="]
N68 --> N71
N72["expr"]
N68 --> N72
N73["identifier: cb"]
N72 --> N73
N74["statement"]
N65 --> N74
N75["block_statement"]
N74 --> N75
N76["begin"]
N75 --> N76
N77["statement"]
N75 --> N77
N78["return_statement"]
N77 --> N78
N79["expr"]
N78 --> N79
N80["literal"]
N79 --> N80
N81["dec: 0"]
N80 --> N81
N82["end"]
N75 --> N82
N83["statement"]
N13 --> N83
N84["if_statement"]
N83 --> N84
N85["if"]
N84 --> N85
N86["expr"]
N84 --> N86
N87["binary_expr"]
N86 --> N87
N88["expr"]
N87 --> N88
N89["identifier: ca"]
N88 --> N89
N90["=="]
N87 --> N90
N91["expr"]
N87 --> N91
N92["literal"]
N91 --> N92
N93["dec: 0"]
N92 --> N93
N94["statement"]
N84 --> N94
N95["block_statement"]
N94 --> N95
N96["begin"]
N95 --> N96
N97["statement"]
N95 --> N97
N98["return_statement"]
N97 --> N98
N99["expr"]
N98 --> N99
N100["literal"]
N99 --> N100
N101["dec: 1"]
N100 --> N101
N102["end"]
N95 --> N102
N103["statement"]
N13 --> N103
N104["expression_statement"]
N103 --> N104
N105["expr"]
N104 --> N105
N106["binary_expr"]
N105 --> N106
N107["expr"]
N106 --> N107
N108["identifier: i"]
N107 --> N108
N109["="]
N106 --> N109
N110["expr"]
N106 --> N110
N111["binary_expr"]
N110 --> N111
N112["expr"]
N111 --> N112
N113["identifier: i"]
N112 --> N113
N114["+"]
N111 --> N114
N115["expr"]
N111 --> N115
N116["literal"]
N115 --> N116
N117["dec: 1"]
N116 --> N117
N118[";"]
N104 --> N118
N119["end"]
N13 --> N119
