graph TD;
N0["function: add"]
N1["statement"]
N0 --> N1
N2["return_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: a"]
N5 --> N6
N7["+"]
N4 --> N7
N8["expr"]
N4 --> N8
N9["identifier: b"]
N8 --> N9
