graph TD
    BB_0["BB0\nt74 = row_buf\[?\]\nt75 = 0\nt76 = t74\[t75\] (str)\nt77 = 0\nt78 = (t76 == t77)\nif t78 goto BB_2 else BB_1"]
    BB_2["BB2\nt79 = 0\nreturn t79"]
    BB_3["BB3\nt84 = true\nif t84 goto BB_4 else BB_5"]
    BB_7["BB7\ngoto BB_5"]
    BB_4["BB4\nt85 = row_buf\[?\]\nt86 = t85\[i\] (str)\nc = t86\nt87 = 0\nt88 = (c == t87)\nif t88 goto BB_7 else BB_6"]
    BB_9["BB9\nt91 = row_buf\[?\]\nt92 = t91\[i\] (str)\nt93 = 0\nt94 = row_buf\[?\]\nt94\[i\] = t93 (str)\nt95 = 1\nt96 = i + t95\nt97 = p_write(col_pipe, t96)\nt98 = 1\nt99 = n + t98\nn = t99\ngoto BB_8"]
    BB_6["BB6\nt89 = 44\nt90 = (c == t89)\nif t90 goto BB_9 else BB_8"]
    BB_8["BB8\nt100 = 1\nt101 = i + t100\ni = t101\ngoto BB_3"]
    BB_1["BB1\n? = p_init(col_pipe)\nt80 = 0\nt81 = p_write(col_pipe, t80)\nt82 = 0\ni = t82\nt83 = 0\nn = t83\ngoto BB_3"]
    BB_10["BB10\nt110 = (ci <= n)\nif t110 goto BB_11 else BB_12"]
    BB_11["BB11\nt111 = co\[ci\]\nt112 = p_read(col_pipe)\nco\[0\] = ?\nt113 = 1\nt114 = ci + t113\nci = t114\ngoto BB_10"]
    BB_5["BB5\nt102 = 1\nt103 = -t102\nt104 = p_write(col_pipe, t103)\nt105 = 0\nt106 = co\[t105\]\nt107 = p_read(col_pipe)\nt108 = 0\nco\[0\] = ?\nt109 = 1\nci = t109\ngoto BB_10"]
    BB_12["BB12\n? = col_drain(col_pipe)\nt115 = 1\nt116 = n + t115\nreturn t116"]
BB_0 --> BB_2
BB_0 --> BB_1
BB_2 --> BB_1
BB_3 --> BB_4
BB_3 --> BB_5
BB_7 --> BB_5
BB_7 --> BB_6
BB_4 --> BB_7
BB_4 --> BB_6
BB_9 --> BB_8
BB_6 --> BB_9
BB_6 --> BB_8
BB_8 --> BB_3
BB_1 --> BB_3
BB_10 --> BB_11
BB_10 --> BB_12
BB_11 --> BB_10
BB_5 --> BB_10
