graph TD;
N0["source"]
N1["func_definition"]
N0 --> N1
N2["func_signature"]
N1 --> N2
N3["identifier: main"]
N2 --> N3
N4["loop_statement"]
N1 --> N4
N5["Less"]
N4 --> N5
N6["i"]
N5 --> N6
N7["5"]
N5 --> N7
N8["expression_statement"]
N4 --> N8
N9["Assign"]
N8 --> N9
N10[""]
N9 --> N10
N11["Add"]
N9 --> N11
N12["i"]
N11 --> N12
N13["1"]
N11 --> N13
N14["expression_statement"]
N1 --> N14
N15["Assign"]
N14 --> N15
N16["a"]
N15 --> N16
N17["fasdfadsf"]
N15 --> N17
N18["expression_statement"]
N1 --> N18
N19["Assign"]
N18 --> N19
N20[""]
N19 --> N20
N21["Add"]
N19 --> N21
N22["Add"]
N21 --> N22
N23["1"]
N22 --> N23
N24["Multiply"]
N22 --> N24
N25["5"]
N24 --> N25
N26["2"]
N24 --> N26
N27["4"]
N21 --> N27
