graph TD
    BB_6["BB6\nt24 = fclose(f)\nt25 = 0\nreturn t25"]
    BB_1["BB1\nt6 = 1\nreturn t6"]
    BB_2["BB2\ngoto BB_3"]
    BB_0["BB0\nt0 = test.csv\nt1 = r\nt2 = fopen(t0, t1)\nf = t2\nt4 = \nt5 = (f == t4)\nif t5 goto BB_1 else BB_2"]
    BB_4["BB4\nt13 = feof(f)\nt14 = 0\nt15 = (t13 == t14)\nif t15 goto BB_5 else BB_6"]
    BB_5["BB5\nt16 = buf\[?\]\nt17 = 256\nt18 = fgets(t16, t17, f)\nt19 = p_count\[?\]\nt20 = p_count\[?\]\nt21 = 1\nt22 = t20 + t21\np_count = t22\ngoto BB_4"]
    BB_3["BB3\nt7 = buf\[?\]\nt8 = 256\nt9 = fgets(t7, t8, f)\nt10 = p_count\[?\]\nt11 = 0\np_count = t11\ngoto BB_4"]
BB_1 --> BB_3
BB_2 --> BB_3
BB_0 --> BB_1
BB_0 --> BB_2
BB_4 --> BB_5
BB_4 --> BB_6
BB_5 --> BB_4
BB_3 --> BB_4
