graph TD;
N0["function: main"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: CORO_COUNT"]
N5 --> N6
N7["="]
N4 --> N7
N8["expr"]
N4 --> N8
N9["literal"]
N8 --> N9
N10["dec: 0"]
N9 --> N10
N11[";"]
N2 --> N11
N12["statement"]
N0 --> N12
N13["expression_statement"]
N12 --> N13
N14["expr"]
N13 --> N14
N15["call_expr"]
N14 --> N15
N16["expr"]
N15 --> N16
N17["identifier: coro_init_nasm"]
N16 --> N17
N18[";"]
N13 --> N18
N19["statement"]
N0 --> N19
N20["expression_statement"]
N19 --> N20
N21["expr"]
N20 --> N21
N22["binary_expr"]
N21 --> N22
N23["expr"]
N22 --> N23
N24["identifier: f0"]
N23 --> N24
N25["="]
N22 --> N25
N26["expr"]
N22 --> N26
N27["literal"]
N26 --> N27
N28["dec: 0"]
N27 --> N28
N29[";"]
N20 --> N29
N30["statement"]
N0 --> N30
N31["expression_statement"]
N30 --> N31
N32["expr"]
N31 --> N32
N33["binary_expr"]
N32 --> N33
N34["expr"]
N33 --> N34
N35["identifier: f1"]
N34 --> N35
N36["="]
N33 --> N36
N37["expr"]
N33 --> N37
N38["literal"]
N37 --> N38
N39["dec: 0"]
N38 --> N39
N40[";"]
N31 --> N40
N41["statement"]
N0 --> N41
N42["loop_statement"]
N41 --> N42
N43["while"]
N42 --> N43
N44["expr"]
N42 --> N44
N45["binary_expr"]
N44 --> N45
N46["expr"]
N45 --> N46
N47["binary_expr"]
N46 --> N47
N48["expr"]
N47 --> N48
N49["identifier: f0"]
N48 --> N49
N50["=="]
N47 --> N50
N51["expr"]
N47 --> N51
N52["literal"]
N51 --> N52
N53["dec: 0"]
N52 --> N53
N54["||"]
N45 --> N54
N55["expr"]
N45 --> N55
N56["binary_expr"]
N55 --> N56
N57["expr"]
N56 --> N57
N58["identifier: f1"]
N57 --> N58
N59["=="]
N56 --> N59
N60["expr"]
N56 --> N60
N61["literal"]
N60 --> N61
N62["dec: 0"]
N61 --> N62
N63["statement"]
N42 --> N63
N64["if_statement"]
N63 --> N64
N65["if"]
N64 --> N65
N66["expr"]
N64 --> N66
N67["binary_expr"]
N66 --> N67
N68["expr"]
N67 --> N68
N69["identifier: f0"]
N68 --> N69
N70["=="]
N67 --> N70
N71["expr"]
N67 --> N71
N72["literal"]
N71 --> N72
N73["dec: 0"]
N72 --> N73
N74["statement"]
N64 --> N74
N75["expression_statement"]
N74 --> N75
N76["expr"]
N75 --> N76
N77["binary_expr"]
N76 --> N77
N78["expr"]
N77 --> N78
N79["identifier: f0"]
N78 --> N79
N80["="]
N77 --> N80
N81["expr"]
N77 --> N81
N82["call_expr"]
N81 --> N82
N83["expr"]
N82 --> N83
N84["identifier: resume_coroutine_nasm"]
N83 --> N84
N85["expr"]
N82 --> N85
N86["binary_expr"]
N85 --> N86
N87["expr"]
N86 --> N87
N88["identifier: CORO_COUNT"]
N87 --> N88
N89["+"]
N86 --> N89
N90["expr"]
N86 --> N90
N91["literal"]
N90 --> N91
N92["dec: 0"]
N91 --> N92
N93[";"]
N75 --> N93
N94["statement"]
N42 --> N94
N95["if_statement"]
N94 --> N95
N96["if"]
N95 --> N96
N97["expr"]
N95 --> N97
N98["binary_expr"]
N97 --> N98
N99["expr"]
N98 --> N99
N100["identifier: f1"]
N99 --> N100
N101["=="]
N98 --> N101
N102["expr"]
N98 --> N102
N103["literal"]
N102 --> N103
N104["dec: 0"]
N103 --> N104
N105["statement"]
N95 --> N105
N106["expression_statement"]
N105 --> N106
N107["expr"]
N106 --> N107
N108["binary_expr"]
N107 --> N108
N109["expr"]
N108 --> N109
N110["identifier: f1"]
N109 --> N110
N111["="]
N108 --> N111
N112["expr"]
N108 --> N112
N113["call_expr"]
N112 --> N113
N114["expr"]
N113 --> N114
N115["identifier: resume_coroutine_nasm"]
N114 --> N115
N116["expr"]
N113 --> N116
N117["binary_expr"]
N116 --> N117
N118["expr"]
N117 --> N118
N119["identifier: CORO_COUNT"]
N118 --> N119
N120["+"]
N117 --> N120
N121["expr"]
N117 --> N121
N122["literal"]
N121 --> N122
N123["dec: 1"]
N122 --> N123
N124[";"]
N106 --> N124
N125["end"]
N42 --> N125
N126["statement"]
N0 --> N126
N127["expression_statement"]
N126 --> N127
N128["expr"]
N127 --> N128
N129["call_expr"]
N128 --> N129
N130["expr"]
N129 --> N130
N131["identifier: puts"]
N130 --> N131
N132["expr"]
N129 --> N132
N133["literal"]
N132 --> N133
N134["str: "done""]
N133 --> N134
N135[";"]
N127 --> N135
N136["statement"]
N0 --> N136
N137["return_statement"]
N136 --> N137
N138["expr"]
N137 --> N138
N139["literal"]
N138 --> N139
N140["dec: 0"]
N139 --> N140
