graph TD
    BB_3["BB3\nt29 = done\nt30 = puts(t29)\nt31 = 0\nreturn t31"]
    BB_1["BB1\nt10 = 0\nt11 = (f0 == t10)\nt12 = 0\nt13 = (f1 == t12)\nt14 = t11 || t13\nif t14 goto BB_2 else BB_3"]
    BB_4["BB4\nt17 = CORO_COUNT\[?\]\nt18 = 0\nt19 = t17 + t18\nt20 = resume_coroutine_nasm(t19)\nf0 = t20\ngoto BB_6"]
    BB_5["BB5\ngoto BB_6"]
    BB_2["BB2\nt15 = 0\nt16 = (f0 == t15)\nif t16 goto BB_4 else BB_5"]
    BB_7["BB7\nt24 = CORO_COUNT\[?\]\nt25 = 1\nt26 = t24 + t25\nt27 = resume_coroutine_nasm(t26)\nf1 = t27\ngoto BB_9"]
    BB_8["BB8\ngoto BB_9"]
    BB_6["BB6\nt22 = 0\nt23 = (f1 == t22)\nif t23 goto BB_7 else BB_8"]
    BB_9["BB9\ngoto BB_1"]
    BB_0["BB0\nt2 = CORO_COUNT\[?\]\nt3 = 0\nCORO_COUNT = t3\nt5 = coro_init_nasm()\nt6 = 0\nf0 = t6\nt8 = 0\nf1 = t8\ngoto BB_1"]
BB_1 --> BB_2
BB_1 --> BB_3
BB_4 --> BB_6
BB_5 --> BB_6
BB_2 --> BB_4
BB_2 --> BB_5
BB_7 --> BB_9
BB_8 --> BB_9
BB_6 --> BB_7
BB_6 --> BB_8
BB_9 --> BB_1
BB_0 --> BB_1
