graph TD
    BB_0["BB0\ngoto BB_1"]
    BB_1["BB1\nt42 = true\nif t42 goto BB_2 else BB_3"]
    BB_5["BB5\nreturn"]
    BB_2["BB2\nt43 = p_read(p)\nt44 = 1\nt45 = -t44\nt46 = (t43 == t45)\nif t46 goto BB_5 else BB_4"]
    BB_4["BB4\ngoto BB_1"]
    BB_3["BB3\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_5 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_4 --> BB_1
