graph TD;
N0["function: read_line"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: pos"]
N5 --> N6
N7["="]
N4 --> N7
N8["expr"]
N4 --> N8
N9["literal"]
N8 --> N9
N10["dec: 0"]
N9 --> N10
N11[";"]
N2 --> N11
N12["statement"]
N0 --> N12
N13["loop_statement"]
N12 --> N13
N14["while"]
N13 --> N14
N15["expr"]
N13 --> N15
N16["literal"]
N15 --> N16
N17["bool: true"]
N16 --> N17
N18["statement"]
N13 --> N18
N19["expression_statement"]
N18 --> N19
N20["expr"]
N19 --> N20
N21["binary_expr"]
N20 --> N21
N22["expr"]
N21 --> N22
N23["identifier: c"]
N22 --> N23
N24["="]
N21 --> N24
N25["expr"]
N21 --> N25
N26["call_expr"]
N25 --> N26
N27["expr"]
N26 --> N27
N28["identifier: fgetc"]
N27 --> N28
N29["expr"]
N26 --> N29
N30["identifier: f"]
N29 --> N30
N31[";"]
N19 --> N31
N32["statement"]
N13 --> N32
N33["if_statement"]
N32 --> N33
N34["if"]
N33 --> N34
N35["expr"]
N33 --> N35
N36["binary_expr"]
N35 --> N36
N37["expr"]
N36 --> N37
N38["identifier: c"]
N37 --> N38
N39["=="]
N36 --> N39
N40["expr"]
N36 --> N40
N41["unary_expr"]
N40 --> N41
N42["-"]
N41 --> N42
N43["expr"]
N41 --> N43
N44["literal"]
N43 --> N44
N45["dec: 1"]
N44 --> N45
N46["statement"]
N33 --> N46
N47["if_statement"]
N46 --> N47
N48["if"]
N47 --> N48
N49["expr"]
N47 --> N49
N50["binary_expr"]
N49 --> N50
N51["expr"]
N50 --> N51
N52["identifier: pos"]
N51 --> N52
N53["=="]
N50 --> N53
N54["expr"]
N50 --> N54
N55["literal"]
N54 --> N55
N56["dec: 0"]
N55 --> N56
N57["statement"]
N47 --> N57
N58["return_statement"]
N57 --> N58
N59["expr"]
N58 --> N59
N60["unary_expr"]
N59 --> N60
N61["-"]
N60 --> N61
N62["expr"]
N60 --> N62
N63["literal"]
N62 --> N63
N64["dec: 1"]
N63 --> N64
N65["statement"]
N33 --> N65
N66["expression_statement"]
N65 --> N66
N67["expr"]
N66 --> N67
N68["binary_expr"]
N67 --> N68
N69["expr"]
N68 --> N69
N70["slice_expr"]
N69 --> N70
N71["expr"]
N70 --> N71
N72["identifier: row_buf"]
N71 --> N72
N73["range"]
N70 --> N73
N74["expr"]
N73 --> N74
N75["identifier: pos"]
N74 --> N75
N76["="]
N68 --> N76
N77["expr"]
N68 --> N77
N78["literal"]
N77 --> N78
N79["dec: 0"]
N78 --> N79
N80[";"]
N66 --> N80
N81["statement"]
N33 --> N81
N82["return_statement"]
N81 --> N82
N83["expr"]
N82 --> N83
N84["literal"]
N83 --> N84
N85["dec: 0"]
N84 --> N85
N86["statement"]
N13 --> N86
N87["if_statement"]
N86 --> N87
N88["if"]
N87 --> N88
N89["expr"]
N87 --> N89
N90["binary_expr"]
N89 --> N90
N91["expr"]
N90 --> N91
N92["identifier: c"]
N91 --> N92
N93["=="]
N90 --> N93
N94["expr"]
N90 --> N94
N95["literal"]
N94 --> N95
N96["dec: 10"]
N95 --> N96
N97["statement"]
N87 --> N97
N98["expression_statement"]
N97 --> N98
N99["expr"]
N98 --> N99
N100["binary_expr"]
N99 --> N100
N101["expr"]
N100 --> N101
N102["slice_expr"]
N101 --> N102
N103["expr"]
N102 --> N103
N104["identifier: row_buf"]
N103 --> N104
N105["range"]
N102 --> N105
N106["expr"]
N105 --> N106
N107["identifier: pos"]
N106 --> N107
N108["="]
N100 --> N108
N109["expr"]
N100 --> N109
N110["literal"]
N109 --> N110
N111["dec: 0"]
N110 --> N111
N112[";"]
N98 --> N112
N113["statement"]
N87 --> N113
N114["return_statement"]
N113 --> N114
N115["expr"]
N114 --> N115
N116["literal"]
N115 --> N116
N117["dec: 0"]
N116 --> N117
N118["statement"]
N13 --> N118
N119["expression_statement"]
N118 --> N119
N120["expr"]
N119 --> N120
N121["binary_expr"]
N120 --> N121
N122["expr"]
N121 --> N122
N123["slice_expr"]
N122 --> N123
N124["expr"]
N123 --> N124
N125["identifier: row_buf"]
N124 --> N125
N126["range"]
N123 --> N126
N127["expr"]
N126 --> N127
N128["identifier: pos"]
N127 --> N128
N129["="]
N121 --> N129
N130["expr"]
N121 --> N130
N131["identifier: c"]
N130 --> N131
N132[";"]
N119 --> N132
N133["statement"]
N13 --> N133
N134["expression_statement"]
N133 --> N134
N135["expr"]
N134 --> N135
N136["binary_expr"]
N135 --> N136
N137["expr"]
N136 --> N137
N138["identifier: pos"]
N137 --> N138
N139["="]
N136 --> N139
N140["expr"]
N136 --> N140
N141["binary_expr"]
N140 --> N141
N142["expr"]
N141 --> N142
N143["identifier: pos"]
N142 --> N143
N144["+"]
N141 --> N144
N145["expr"]
N141 --> N145
N146["literal"]
N145 --> N146
N147["dec: 1"]
N146 --> N147
N148[";"]
N134 --> N148
