graph TD
    BB_0["BB0\nt8 = 0\nf0 = t8\nt9 = 0\nf1 = t9\ngoto BB_1"]
    BB_1["BB1\nt10 = 0\nt11 = (f0 == t10)\nt12 = 0\nt13 = (f1 == t12)\nt14 = t11 || t13\nif t14 goto BB_2 else BB_3"]
    BB_5["BB5\nt17 = 0\nt18 = resume_coroutine(t17)\nf0 = t18\ngoto BB_4"]
    BB_2["BB2\nt15 = 0\nt16 = (f0 == t15)\nif t16 goto BB_5 else BB_4"]
    BB_7["BB7\nt21 = 1\nt22 = resume_coroutine(t21)\nf1 = t22\ngoto BB_6"]
    BB_4["BB4\nt19 = 0\nt20 = (f1 == t19)\nif t20 goto BB_7 else BB_6"]
    BB_6["BB6\ngoto BB_1"]
    BB_3["BB3\nt23 = 0\nreturn t23"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_5 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_7 --> BB_6
BB_4 --> BB_7
BB_4 --> BB_6
BB_6 --> BB_1
