graph TD
    BB_0["BB0\nt129 = 0\ni = t129\ngoto BB_1"]
    BB_1["BB1\nt130 = true\nif t130 goto BB_2 else BB_3"]
    BB_5["BB5\nt136 = 0\nreturn t136"]
    BB_2["BB2\nt131 = a + i\nt132 = buf\[t131\] (str)\nca = t132\nt133 = b + i\nt134 = buf\[t133\] (str)\ncb = t134\nt135 = (ca != cb)\nif t135 goto BB_5 else BB_4"]
    BB_7["BB7\nt139 = 1\nreturn t139"]
    BB_4["BB4\nt137 = 0\nt138 = (ca == t137)\nif t138 goto BB_7 else BB_6"]
    BB_6["BB6\nt140 = 1\nt141 = i + t140\ni = t141\ngoto BB_1"]
    BB_3["BB3\n"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_5 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_7 --> BB_6
BB_4 --> BB_7
BB_4 --> BB_6
BB_6 --> BB_1
