graph TD
    BB_0["BB0\nt648 = 0\nsum = t648\nt649 = 0\ncnt = t649\nt650 = 0\ni = t650\ngoto BB_1"]
    BB_1["BB1\nt651 = sd_n\[?\]\nt652 = (i < t651)\nif t652 goto BB_2 else BB_3"]
    BB_6["BB6\nt660 = vv_n\[?\]\nt661 = (j < t660)\nif t661 goto BB_7 else BB_8"]
    BB_10["BB10\nt668 = vv_mark\[j\]\nt669 = sum + t668\nsum = t669\nt670 = 1\nt671 = cnt + t670\ncnt = t671\ngoto BB_9"]
    BB_7["BB7\nt662 = vv_pid\[j\]\nt663 = (t662 == pid)\nt664 = vv_mark\[j\]\nt665 = 3\nt666 = (t664 >= t665)\nt667 = t663 && t666\nif t667 goto BB_10 else BB_9"]
    BB_9["BB9\nt672 = 1\nt673 = j + t672\nj = t673\ngoto BB_6"]
    BB_5["BB5\nt658 = sd_pid\[i\]\npid = t658\nt659 = 0\nj = t659\ngoto BB_6"]
    BB_8["BB8\ngoto BB_4"]
    BB_2["BB2\nt653 = sd_buf\[?\]\nt654 = sd_group\[i\]\nt655 = str_eq_lit(t653, t654, grp)\nt656 = 0\nt657 = (t655 != t656)\nif t657 goto BB_5 else BB_4"]
    BB_4["BB4\nt674 = 1\nt675 = i + t674\ni = t675\ngoto BB_1"]
    BB_12["BB12\nt678 = 0\nreturn t678"]
    BB_3["BB3\nt676 = 0\nt677 = (cnt == t676)\nif t677 goto BB_12 else BB_11"]
    BB_11["BB11\nt679 = 10\nt680 = sum * t679\nt681 = t680 / cnt\nreturn t681"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_6 --> BB_7
BB_6 --> BB_8
BB_10 --> BB_9
BB_7 --> BB_10
BB_7 --> BB_9
BB_9 --> BB_6
BB_5 --> BB_6
BB_8 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_4 --> BB_1
BB_12 --> BB_11
BB_3 --> BB_12
BB_3 --> BB_11
