graph TD
    BB_0["BB0\nt600 = === Q4: Plans >2 groups on CE ===\nt601 = puts(t600)\nt602 = 0\ni = t602\ngoto BB_1"]
    BB_1["BB1\nt603 = 50\nt604 = (i < t603)\nif t604 goto BB_2 else BB_3"]
    BB_2["BB2\nt605 = w\[i\]\nt606 = 0\nw\[0\] = ?\nt607 = 1\nt608 = i + t607\ni = t608\ngoto BB_1"]
    BB_4["BB4\nt610 = gp_n\[?\]\nt611 = (i < t610)\nif t611 goto BB_5 else BB_6"]
    BB_9["BB9\nt625 = gp_n\[?\]\nt626 = (j < t625)\nif t626 goto BB_10 else BB_11"]
    BB_13["BB13\nt636 = 1\nt637 = cnt + t636\ncnt = t637\nt638 = w\[j\]\nt639 = 1\nw\[0\] = ?\ngoto BB_12"]
    BB_10["BB10\nt627 = gp_pid\[j\]\nt628 = (t627 == pid)\nt629 = gp_buf\[?\]\nt630 = gp_dept\[j\]\nt631 = Department of Computer Engineering\nt632 = str_eq_lit(t629, t630, t631)\nt633 = 0\nt634 = (t632 != t633)\nt635 = t628 && t634\nif t635 goto BB_13 else BB_12"]
    BB_12["BB12\nt640 = 1\nt641 = j + t640\nj = t641\ngoto BB_9"]
    BB_8["BB8\nt622 = gp_pid\[i\]\npid = t622\nt623 = 0\ncnt = t623\nt624 = 0\nj = t624\ngoto BB_9"]
    BB_15["BB15\nt644 = %d: %d groups\\n\nt645 = printf(t644, pid, cnt)\ngoto BB_14"]
    BB_11["BB11\nt642 = 2\nt643 = (cnt > t642)\nif t643 goto BB_15 else BB_14"]
    BB_14["BB14\ngoto BB_7"]
    BB_5["BB5\nt612 = w\[i\]\nt613 = 0\nt614 = (t612 == t613)\nt615 = gp_buf\[?\]\nt616 = gp_dept\[i\]\nt617 = Department of Computer Engineering\nt618 = str_eq_lit(t615, t616, t617)\nt619 = 0\nt620 = (t618 != t619)\nt621 = t614 && t620\nif t621 goto BB_8 else BB_7"]
    BB_7["BB7\nt646 = 1\nt647 = i + t646\ni = t647\ngoto BB_4"]
    BB_3["BB3\nt609 = 0\ni = t609\ngoto BB_4"]
    BB_6["BB6\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_2 --> BB_1
BB_4 --> BB_5
BB_4 --> BB_6
BB_9 --> BB_10
BB_9 --> BB_11
BB_13 --> BB_12
BB_10 --> BB_13
BB_10 --> BB_12
BB_12 --> BB_9
BB_8 --> BB_9
BB_15 --> BB_14
BB_11 --> BB_15
BB_11 --> BB_14
BB_14 --> BB_7
BB_5 --> BB_8
BB_5 --> BB_7
BB_7 --> BB_4
BB_3 --> BB_4
