graph TD
    BB_0["BB0\nt753 = === Q6: Enrolled after 2012-09-01, 1 course, part-time ===\nt754 = puts(t753)\nt755 = 0\ncount = t755\nt756 = 0\ni = t756\ngoto BB_1"]
    BB_1["BB1\nt757 = sd_n\[?\]\nt758 = (i < t757)\nif t758 goto BB_2 else BB_3"]
    BB_6["BB6\nt767 = st_n\[?\]\nt768 = (si < t767)\nif t768 goto BB_7 else BB_8"]
    BB_11["BB11\nt785 = pp_n\[?\]\nt786 = (pi < t785)\nif t786 goto BB_12 else BB_13"]
    BB_15["BB15\nt789 = sd_buf\[?\]\nt790 = sd_group\[i\]\n? = print_str(t789, t790)\nt791 = 44\nt792 = putchar(t791)\nt793 = 32\nt794 = putchar(t793)\nt795 = %d\nt796 = printf(t795, pid)\nt797 = 44\nt798 = putchar(t797)\nt799 = 32\nt800 = putchar(t799)\nt801 = pp_buf\[?\]\nt802 = pp_surname\[pi\]\n? = print_str(t801, t802)\nt803 = 32\nt804 = putchar(t803)\nt805 = pp_buf\[?\]\nt806 = pp_name\[pi\]\n? = print_str(t805, t806)\nt807 = 10\nt808 = putchar(t807)\ngoto BB_14"]
    BB_12["BB12\nt787 = pp_id\[pi\]\nt788 = (t787 == pid)\nif t788 goto BB_15 else BB_14"]
    BB_14["BB14\nt809 = 1\nt810 = pi + t809\npi = t810\ngoto BB_11"]
    BB_10["BB10\nt782 = 1\nt783 = count + t782\ncount = t783\nt784 = 0\npi = t784\ngoto BB_11"]
    BB_13["BB13\ngoto BB_8"]
    BB_7["BB7\nt769 = st_pid\[si\]\nt770 = (t769 == pid)\nt771 = st_buf\[?\]\nt772 = st_form\[si\]\nt773 = part-time\nt774 = str_eq_lit(t771, t772, t773)\nt775 = 0\nt776 = (t774 != t775)\nt777 = t770 && t776\nt778 = st_course\[si\]\nt779 = 1\nt780 = (t778 == t779)\nt781 = t777 && t780\nif t781 goto BB_10 else BB_9"]
    BB_9["BB9\nt811 = 1\nt812 = si + t811\nsi = t812\ngoto BB_6"]
    BB_5["BB5\nt765 = sd_pid\[i\]\npid = t765\nt766 = 0\nsi = t766\ngoto BB_6"]
    BB_8["BB8\ngoto BB_4"]
    BB_2["BB2\nt759 = sd_buf\[?\]\nt760 = sd_start\[i\]\nt761 = 2012-09-01\nt762 = str_gt_lit(t759, t760, t761)\nt763 = 0\nt764 = (t762 > t763)\nif t764 goto BB_5 else BB_4"]
    BB_4["BB4\nt813 = 1\nt814 = i + t813\ni = t814\ngoto BB_1"]
    BB_3["BB3\nt815 = Count: %d\\n\nt816 = printf(t815, count)\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_6 --> BB_7
BB_6 --> BB_8
BB_11 --> BB_12
BB_11 --> BB_13
BB_15 --> BB_14
BB_12 --> BB_15
BB_12 --> BB_14
BB_14 --> BB_11
BB_10 --> BB_11
BB_13 --> BB_8
BB_13 --> BB_9
BB_7 --> BB_10
BB_7 --> BB_9
BB_9 --> BB_6
BB_5 --> BB_6
BB_8 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_4 --> BB_1
