graph TD;
N0["source"]
N1["source_item"]
N0 --> N1
N2["def"]
N1 --> N2
N3["func_signature"]
N1 --> N3
N4["identifier: main"]
N3 --> N4
N5["("]
N3 --> N5
N6[")"]
N3 --> N6
N7["statement"]
N1 --> N7
N8["expression_statement"]
N7 --> N8
N9["expr"]
N8 --> N9
N10["binary_expr"]
N9 --> N10
N11["expr"]
N10 --> N11
N12["slice_expr"]
N11 --> N12
N13["expr"]
N12 --> N13
N14["identifier: arr"]
N13 --> N14
N15["range"]
N12 --> N15
N16["expr"]
N15 --> N16
N17["literal"]
N16 --> N17
N18["dec: 0"]
N17 --> N18
N19["="]
N10 --> N19
N20["expr"]
N10 --> N20
N21["literal"]
N20 --> N21
N22["dec: 1"]
N21 --> N22
N23[";"]
N8 --> N23
N24["end"]
N1 --> N24
