graph TD;
N0["function: buf_clear"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["call_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: strcpy"]
N5 --> N6
N7["expr"]
N4 --> N7
N8["identifier: b"]
N7 --> N8
N9["expr"]
N4 --> N9
N10["literal"]
N9 --> N10
N11["str: """]
N10 --> N11
N12[";"]
N2 --> N12
