graph TD;
N0["function: int_to_str"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["call_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: buf_clear"]
N5 --> N6
N7["expr"]
N4 --> N7
N8["identifier: dst"]
N7 --> N8
N9[";"]
N2 --> N9
N10["statement"]
N0 --> N10
N11["if_statement"]
N10 --> N11
N12["if"]
N11 --> N12
N13["expr"]
N11 --> N13
N14["binary_expr"]
N13 --> N14
N15["expr"]
N14 --> N15
N16["identifier: val"]
N15 --> N16
N17["<"]
N14 --> N17
N18["expr"]
N14 --> N18
N19["literal"]
N18 --> N19
N20["dec: 0"]
N19 --> N20
N21["statement"]
N11 --> N21
N22["block_statement"]
N21 --> N22
N23["begin"]
N22 --> N23
N24["statement"]
N22 --> N24
N25["expression_statement"]
N24 --> N25
N26["expr"]
N25 --> N26
N27["call_expr"]
N26 --> N27
N28["expr"]
N27 --> N28
N29["identifier: strcat"]
N28 --> N29
N30["expr"]
N27 --> N30
N31["identifier: dst"]
N30 --> N31
N32["expr"]
N27 --> N32
N33["literal"]
N32 --> N33
N34["str: "-""]
N33 --> N34
N35[";"]
N25 --> N35
N36["statement"]
N22 --> N36
N37["expression_statement"]
N36 --> N37
N38["expr"]
N37 --> N38
N39["binary_expr"]
N38 --> N39
N40["expr"]
N39 --> N40
N41["identifier: val"]
N40 --> N41
N42["="]
N39 --> N42
N43["expr"]
N39 --> N43
N44["binary_expr"]
N43 --> N44
N45["expr"]
N44 --> N45
N46["literal"]
N45 --> N46
N47["dec: 0"]
N46 --> N47
N48["-"]
N44 --> N48
N49["expr"]
N44 --> N49
N50["identifier: val"]
N49 --> N50
N51[";"]
N37 --> N51
N52["end"]
N22 --> N52
N53["statement"]
N0 --> N53
N54["if_statement"]
N53 --> N54
N55["if"]
N54 --> N55
N56["expr"]
N54 --> N56
N57["binary_expr"]
N56 --> N57
N58["expr"]
N57 --> N58
N59["identifier: val"]
N58 --> N59
N60[">="]
N57 --> N60
N61["expr"]
N57 --> N61
N62["literal"]
N61 --> N62
N63["dec: 10"]
N62 --> N63
N64["statement"]
N54 --> N64
N65["block_statement"]
N64 --> N65
N66["begin"]
N65 --> N66
N67["statement"]
N65 --> N67
N68["expression_statement"]
N67 --> N68
N69["expr"]
N68 --> N69
N70["call_expr"]
N69 --> N70
N71["expr"]
N70 --> N71
N72["identifier: int_to_str"]
N71 --> N72
N73["expr"]
N70 --> N73
N74["identifier: dst"]
N73 --> N74
N75["expr"]
N70 --> N75
N76["binary_expr"]
N75 --> N76
N77["expr"]
N76 --> N77
N78["identifier: val"]
N77 --> N78
N79["/"]
N76 --> N79
N80["expr"]
N76 --> N80
N81["literal"]
N80 --> N81
N82["dec: 10"]
N81 --> N82
N83[";"]
N68 --> N83
N84["end"]
N65 --> N84
N85["statement"]
N0 --> N85
N86["expression_statement"]
N85 --> N86
N87["expr"]
N86 --> N87
N88["call_expr"]
N87 --> N88
N89["expr"]
N88 --> N89
N90["identifier: choose_digit"]
N89 --> N90
N91["expr"]
N88 --> N91
N92["identifier: dst"]
N91 --> N92
N93["expr"]
N88 --> N93
N94["binary_expr"]
N93 --> N94
N95["expr"]
N94 --> N95
N96["identifier: val"]
N95 --> N96
N97["-"]
N94 --> N97
N98["expr"]
N94 --> N98
N99["binary_expr"]
N98 --> N99
N100["expr"]
N99 --> N100
N101["parenthesized_expr"]
N100 --> N101
N102["expr"]
N101 --> N102
N103["binary_expr"]
N102 --> N103
N104["expr"]
N103 --> N104
N105["identifier: val"]
N104 --> N105
N106["/"]
N103 --> N106
N107["expr"]
N103 --> N107
N108["literal"]
N107 --> N108
N109["dec: 10"]
N108 --> N109
N110["*"]
N99 --> N110
N111["expr"]
N99 --> N111
N112["literal"]
N111 --> N112
N113["dec: 10"]
N112 --> N113
N114[";"]
N86 --> N114
