graph TD
    BB_0["BB0\nt188 = r\nt189 = fopen(fn, t188)\nf = t189\nt190 = 0\nt191 = (f == t190)\nif t191 goto BB_2 else BB_1"]
    BB_2["BB2\nt192 = 1\nt193 = -t192\nreturn t193"]
    BB_3["BB3\nt201 = true\nif t201 goto BB_4 else BB_5"]
    BB_7["BB7\ngoto BB_5"]
    BB_4["BB4\nt202 = read_line(f)\nt203 = 1\nt204 = -t203\nt205 = (t202 == t204)\nif t205 goto BB_7 else BB_6"]
    BB_6["BB6\nt206 = parse_row()\nt207 = tv_n\[?\]\nt208 = tv_id\[t207\]\nt209 = row_buf\[?\]\nt210 = 0\nt211 = co\[t210\]\nt212 = t209 + t211\nt213 = atoi(t212)\nt214 = tv_n\[?\]\ntv_id\[0\] = ?\nt215 = tv_n\[?\]\nt216 = tv_name\[t215\]\nt217 = tv_n\[?\]\ntv_name\[0\] = ?\nt218 = tv_buf\[?\]\nt219 = 1\nt220 = co\[t219\]\nt221 = str_save(t218, pos, t220)\npos = t221\nt222 = tv_n\[?\]\nt223 = tv_n\[?\]\nt224 = 1\nt225 = t223 + t224\ntv_n = t225\ngoto BB_3"]
    BB_1["BB1\nt194 = read_line(f)\nt195 = tv_n\[?\]\nt196 = 0\ntv_n = t196\nt197 = tv_buf\[?\]\nt198 = 1000\nt199 = malloc(t198)\ntv_buf = t199\nt200 = 0\npos = t200\ngoto BB_3"]
    BB_5["BB5\nt226 = fclose(f)\nt227 = tv_n\[?\]\nreturn t227"]
BB_0 --> BB_2
BB_0 --> BB_1
BB_2 --> BB_1
BB_3 --> BB_4
BB_3 --> BB_5
BB_7 --> BB_5
BB_7 --> BB_6
BB_4 --> BB_7
BB_4 --> BB_6
BB_6 --> BB_3
BB_1 --> BB_3
