graph TD
    BB_0["BB0\ni = ofs\ngoto BB_1"]
    BB_1["BB1\nt181 = true\nif t181 goto BB_2 else BB_3"]
    BB_5["BB5\ngoto BB_3"]
    BB_2["BB2\nt182 = buf\[i\] (str)\nc = t182\nt183 = 0\nt184 = (c == t183)\nif t184 goto BB_5 else BB_4"]
    BB_4["BB4\nt185 = putchar(c)\nt186 = 1\nt187 = i + t186\ni = t187\ngoto BB_1"]
    BB_3["BB3\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_5 --> BB_3
BB_5 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_4 --> BB_1
