graph TD
    BB_0["BB0\nt47 = 0\npos = t47\ngoto BB_1"]
    BB_1["BB1\nt48 = true\nif t48 goto BB_2 else BB_3"]
    BB_7["BB7\nt55 = 1\nt56 = -t55\nreturn t56"]
    BB_5["BB5\nt53 = 0\nt54 = (pos == t53)\nif t54 goto BB_7 else BB_6"]
    BB_6["BB6\nt57 = row_buf\[?\]\nt58 = t57\[pos\] (str)\nt59 = 0\nt60 = row_buf\[?\]\nt60\[pos\] = t59 (str)\nt61 = 0\nreturn t61"]
    BB_2["BB2\nt49 = fgetc(f)\nc = t49\nt50 = 1\nt51 = -t50\nt52 = (c == t51)\nif t52 goto BB_5 else BB_4"]
    BB_9["BB9\nt64 = row_buf\[?\]\nt65 = t64\[pos\] (str)\nt66 = 0\nt67 = row_buf\[?\]\nt67\[pos\] = t66 (str)\nt68 = 0\nreturn t68"]
    BB_4["BB4\nt62 = 10\nt63 = (c == t62)\nif t63 goto BB_9 else BB_8"]
    BB_8["BB8\nt69 = row_buf\[?\]\nt70 = t69\[pos\] (str)\nt71 = row_buf\[?\]\nt71\[pos\] = c (str)\nt72 = 1\nt73 = pos + t72\npos = t73\ngoto BB_1"]
    BB_3["BB3\n"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_7 --> BB_6
BB_5 --> BB_7
BB_5 --> BB_6
BB_6 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_9 --> BB_8
BB_4 --> BB_9
BB_4 --> BB_8
BB_8 --> BB_1
