graph TD;
N0["function: col_drain"]
N1["statement"]
N0 --> N1
N2["loop_statement"]
N1 --> N2
N3["while"]
N2 --> N3
N4["expr"]
N2 --> N4
N5["literal"]
N4 --> N5
N6["bool: true"]
N5 --> N6
N7["statement"]
N2 --> N7
N8["if_statement"]
N7 --> N8
N9["if"]
N8 --> N9
N10["expr"]
N8 --> N10
N11["binary_expr"]
N10 --> N11
N12["expr"]
N11 --> N12
N13["call_expr"]
N12 --> N13
N14["expr"]
N13 --> N14
N15["identifier: p_read"]
N14 --> N15
N16["expr"]
N13 --> N16
N17["identifier: p"]
N16 --> N17
N18["=="]
N11 --> N18
N19["expr"]
N11 --> N19
N20["unary_expr"]
N19 --> N20
N21["-"]
N20 --> N21
N22["expr"]
N20 --> N22
N23["literal"]
N22 --> N23
N24["dec: 1"]
N23 --> N24
N25["statement"]
N8 --> N25
N26["return_statement"]
N25 --> N26
