graph TD
    BB_0["BB0\nt176 = buf\[off\] (str)\nt177 = 0\nt178 = (t176 == t177)\nif t178 goto BB_2 else BB_1"]
    BB_2["BB2\nt179 = 1\nreturn t179"]
    BB_1["BB1\nt180 = 0\nreturn t180"]
BB_0 --> BB_2
BB_0 --> BB_1
BB_2 --> BB_1
