graph TD
    BB_3["BB3\nt11 = closed\nt12 = puts(t11)\nt13 = 0\nreturn t13"]
    BB_1["BB1\nt10 = fclose(f)\ngoto BB_3"]
    BB_2["BB2\ngoto BB_3"]
    BB_0["BB0\nt0 = start\nt1 = puts(t0)\nt2 = labs-examples/system-programms/lab-2/csv-data/people.csv\nt3 = r\nt4 = fopen(t2, t3)\nf = t4\nt6 = opened\nt7 = puts(t6)\nt8 = \nt9 = (f != t8)\nif t9 goto BB_1 else BB_2"]
BB_1 --> BB_3
BB_2 --> BB_3
BB_0 --> BB_1
BB_0 --> BB_2
