graph TD
    BB_3["BB3\nt48 = done\nt49 = puts(t48)\nt50 = 0\nreturn t50"]
    BB_1["BB1\nt25 = 0\nt26 = (f0 == t25)\nt27 = 0\nt28 = (f1 == t27)\nt29 = t26 || t28\nt30 = 0\nt31 = (f2 == t30)\nt32 = t29 || t31\nif t32 goto BB_2 else BB_3"]
    BB_4["BB4\nt35 = 0\nt36 = resume_coroutine_nasm(t35)\nf0 = t36\ngoto BB_6"]
    BB_5["BB5\ngoto BB_6"]
    BB_2["BB2\nt33 = 0\nt34 = (f0 == t33)\nif t34 goto BB_4 else BB_5"]
    BB_7["BB7\nt40 = 1\nt41 = resume_coroutine_nasm(t40)\nf1 = t41\ngoto BB_9"]
    BB_8["BB8\ngoto BB_9"]
    BB_6["BB6\nt38 = 0\nt39 = (f1 == t38)\nif t39 goto BB_7 else BB_8"]
    BB_10["BB10\nt45 = 2\nt46 = resume_coroutine_nasm(t45)\nf2 = t46\ngoto BB_12"]
    BB_11["BB11\ngoto BB_12"]
    BB_9["BB9\nt43 = 0\nt44 = (f2 == t43)\nif t44 goto BB_10 else BB_11"]
    BB_12["BB12\ngoto BB_1"]
    BB_0["BB0\nt18 = coro_init_nasm()\nt19 = 0\nf0 = t19\nt21 = 0\nf1 = t21\nt23 = 0\nf2 = t23\ngoto BB_1"]
BB_1 --> BB_2
BB_1 --> BB_3
BB_4 --> BB_6
BB_5 --> BB_6
BB_2 --> BB_4
BB_2 --> BB_5
BB_7 --> BB_9
BB_8 --> BB_9
BB_6 --> BB_7
BB_6 --> BB_8
BB_10 --> BB_12
BB_11 --> BB_12
BB_9 --> BB_10
BB_9 --> BB_11
BB_12 --> BB_1
BB_0 --> BB_1
