graph TD;
N0["function: main"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["call_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: coro_init_nasm"]
N5 --> N6
N7[";"]
N2 --> N7
N8["statement"]
N0 --> N8
N9["expression_statement"]
N8 --> N9
N10["expr"]
N9 --> N10
N11["binary_expr"]
N10 --> N11
N12["expr"]
N11 --> N12
N13["identifier: f0"]
N12 --> N13
N14["="]
N11 --> N14
N15["expr"]
N11 --> N15
N16["literal"]
N15 --> N16
N17["dec: 0"]
N16 --> N17
N18[";"]
N9 --> N18
N19["statement"]
N0 --> N19
N20["expression_statement"]
N19 --> N20
N21["expr"]
N20 --> N21
N22["binary_expr"]
N21 --> N22
N23["expr"]
N22 --> N23
N24["identifier: f1"]
N23 --> N24
N25["="]
N22 --> N25
N26["expr"]
N22 --> N26
N27["literal"]
N26 --> N27
N28["dec: 0"]
N27 --> N28
N29[";"]
N20 --> N29
N30["statement"]
N0 --> N30
N31["expression_statement"]
N30 --> N31
N32["expr"]
N31 --> N32
N33["binary_expr"]
N32 --> N33
N34["expr"]
N33 --> N34
N35["identifier: f2"]
N34 --> N35
N36["="]
N33 --> N36
N37["expr"]
N33 --> N37
N38["literal"]
N37 --> N38
N39["dec: 0"]
N38 --> N39
N40[";"]
N31 --> N40
N41["statement"]
N0 --> N41
N42["loop_statement"]
N41 --> N42
N43["while"]
N42 --> N43
N44["expr"]
N42 --> N44
N45["binary_expr"]
N44 --> N45
N46["expr"]
N45 --> N46
N47["binary_expr"]
N46 --> N47
N48["expr"]
N47 --> N48
N49["binary_expr"]
N48 --> N49
N50["expr"]
N49 --> N50
N51["identifier: f0"]
N50 --> N51
N52["=="]
N49 --> N52
N53["expr"]
N49 --> N53
N54["literal"]
N53 --> N54
N55["dec: 0"]
N54 --> N55
N56["||"]
N47 --> N56
N57["expr"]
N47 --> N57
N58["binary_expr"]
N57 --> N58
N59["expr"]
N58 --> N59
N60["identifier: f1"]
N59 --> N60
N61["=="]
N58 --> N61
N62["expr"]
N58 --> N62
N63["literal"]
N62 --> N63
N64["dec: 0"]
N63 --> N64
N65["||"]
N45 --> N65
N66["expr"]
N45 --> N66
N67["binary_expr"]
N66 --> N67
N68["expr"]
N67 --> N68
N69["identifier: f2"]
N68 --> N69
N70["=="]
N67 --> N70
N71["expr"]
N67 --> N71
N72["literal"]
N71 --> N72
N73["dec: 0"]
N72 --> N73
N74["statement"]
N42 --> N74
N75["if_statement"]
N74 --> N75
N76["if"]
N75 --> N76
N77["expr"]
N75 --> N77
N78["binary_expr"]
N77 --> N78
N79["expr"]
N78 --> N79
N80["identifier: f0"]
N79 --> N80
N81["=="]
N78 --> N81
N82["expr"]
N78 --> N82
N83["literal"]
N82 --> N83
N84["dec: 0"]
N83 --> N84
N85["statement"]
N75 --> N85
N86["expression_statement"]
N85 --> N86
N87["expr"]
N86 --> N87
N88["binary_expr"]
N87 --> N88
N89["expr"]
N88 --> N89
N90["identifier: f0"]
N89 --> N90
N91["="]
N88 --> N91
N92["expr"]
N88 --> N92
N93["call_expr"]
N92 --> N93
N94["expr"]
N93 --> N94
N95["identifier: resume_coroutine_nasm"]
N94 --> N95
N96["expr"]
N93 --> N96
N97["literal"]
N96 --> N97
N98["dec: 0"]
N97 --> N98
N99[";"]
N86 --> N99
N100["statement"]
N42 --> N100
N101["if_statement"]
N100 --> N101
N102["if"]
N101 --> N102
N103["expr"]
N101 --> N103
N104["binary_expr"]
N103 --> N104
N105["expr"]
N104 --> N105
N106["identifier: f1"]
N105 --> N106
N107["=="]
N104 --> N107
N108["expr"]
N104 --> N108
N109["literal"]
N108 --> N109
N110["dec: 0"]
N109 --> N110
N111["statement"]
N101 --> N111
N112["expression_statement"]
N111 --> N112
N113["expr"]
N112 --> N113
N114["binary_expr"]
N113 --> N114
N115["expr"]
N114 --> N115
N116["identifier: f1"]
N115 --> N116
N117["="]
N114 --> N117
N118["expr"]
N114 --> N118
N119["call_expr"]
N118 --> N119
N120["expr"]
N119 --> N120
N121["identifier: resume_coroutine_nasm"]
N120 --> N121
N122["expr"]
N119 --> N122
N123["literal"]
N122 --> N123
N124["dec: 1"]
N123 --> N124
N125[";"]
N112 --> N125
N126["statement"]
N42 --> N126
N127["if_statement"]
N126 --> N127
N128["if"]
N127 --> N128
N129["expr"]
N127 --> N129
N130["binary_expr"]
N129 --> N130
N131["expr"]
N130 --> N131
N132["identifier: f2"]
N131 --> N132
N133["=="]
N130 --> N133
N134["expr"]
N130 --> N134
N135["literal"]
N134 --> N135
N136["dec: 0"]
N135 --> N136
N137["statement"]
N127 --> N137
N138["expression_statement"]
N137 --> N138
N139["expr"]
N138 --> N139
N140["binary_expr"]
N139 --> N140
N141["expr"]
N140 --> N141
N142["identifier: f2"]
N141 --> N142
N143["="]
N140 --> N143
N144["expr"]
N140 --> N144
N145["call_expr"]
N144 --> N145
N146["expr"]
N145 --> N146
N147["identifier: resume_coroutine_nasm"]
N146 --> N147
N148["expr"]
N145 --> N148
N149["literal"]
N148 --> N149
N150["dec: 2"]
N149 --> N150
N151[";"]
N138 --> N151
N152["end"]
N42 --> N152
N153["statement"]
N0 --> N153
N154["expression_statement"]
N153 --> N154
N155["expr"]
N154 --> N155
N156["call_expr"]
N155 --> N156
N157["expr"]
N156 --> N157
N158["identifier: puts"]
N157 --> N158
N159["expr"]
N156 --> N159
N160["literal"]
N159 --> N160
N161["str: "done""]
N160 --> N161
N162[";"]
N154 --> N162
N163["statement"]
N0 --> N163
N164["return_statement"]
N163 --> N164
N165["expr"]
N164 --> N165
N166["literal"]
N165 --> N166
N167["dec: 0"]
N166 --> N167
