graph TD;
N0["function: main"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["call_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: puts"]
N5 --> N6
N7["expr"]
N4 --> N7
N8["literal"]
N7 --> N8
N9["str: "start""]
N8 --> N9
N10[";"]
N2 --> N10
N11["statement"]
N0 --> N11
N12["expression_statement"]
N11 --> N12
N13["expr"]
N12 --> N13
N14["binary_expr"]
N13 --> N14
N15["expr"]
N14 --> N15
N16["identifier: f"]
N15 --> N16
N17["="]
N14 --> N17
N18["expr"]
N14 --> N18
N19["call_expr"]
N18 --> N19
N20["expr"]
N19 --> N20
N21["identifier: fopen"]
N20 --> N21
N22["expr"]
N19 --> N22
N23["literal"]
N22 --> N23
N24["str: "labs-examples/system-programms/lab-2/csv-data/people.csv""]
N23 --> N24
N25["expr"]
N19 --> N25
N26["literal"]
N25 --> N26
N27["str: "r""]
N26 --> N27
N28[";"]
N12 --> N28
N29["statement"]
N0 --> N29
N30["expression_statement"]
N29 --> N30
N31["expr"]
N30 --> N31
N32["call_expr"]
N31 --> N32
N33["expr"]
N32 --> N33
N34["identifier: puts"]
N33 --> N34
N35["expr"]
N32 --> N35
N36["literal"]
N35 --> N36
N37["str: "opened""]
N36 --> N37
N38[";"]
N30 --> N38
N39["statement"]
N0 --> N39
N40["expression_statement"]
N39 --> N40
N41["expr"]
N40 --> N41
N42["binary_expr"]
N41 --> N42
N43["expr"]
N42 --> N43
N44["identifier: c"]
N43 --> N44
N45["="]
N42 --> N45
N46["expr"]
N42 --> N46
N47["call_expr"]
N46 --> N47
N48["expr"]
N47 --> N48
N49["identifier: fgetc"]
N48 --> N49
N50["expr"]
N47 --> N50
N51["identifier: f"]
N50 --> N51
N52[";"]
N40 --> N52
N53["statement"]
N0 --> N53
N54["expression_statement"]
N53 --> N54
N55["expr"]
N54 --> N55
N56["call_expr"]
N55 --> N56
N57["expr"]
N56 --> N57
N58["identifier: puts"]
N57 --> N58
N59["expr"]
N56 --> N59
N60["literal"]
N59 --> N60
N61["str: "read one char""]
N60 --> N61
N62[";"]
N54 --> N62
N63["statement"]
N0 --> N63
N64["expression_statement"]
N63 --> N64
N65["expr"]
N64 --> N65
N66["call_expr"]
N65 --> N66
N67["expr"]
N66 --> N67
N68["identifier: fclose"]
N67 --> N68
N69["expr"]
N66 --> N69
N70["identifier: f"]
N69 --> N70
N71[";"]
N64 --> N71
N72["statement"]
N0 --> N72
N73["expression_statement"]
N72 --> N73
N74["expr"]
N73 --> N74
N75["call_expr"]
N74 --> N75
N76["expr"]
N75 --> N76
N77["identifier: puts"]
N76 --> N77
N78["expr"]
N75 --> N78
N79["literal"]
N78 --> N79
N80["str: "done""]
N79 --> N80
N81[";"]
N73 --> N81
N82["statement"]
N0 --> N82
N83["return_statement"]
N82 --> N83
N84["expr"]
N83 --> N84
N85["literal"]
N84 --> N85
N86["dec: 0"]
N85 --> N86
