graph TD
    BB_0["BB0\nt0 = start\nt1 = puts(t0)\nt2 = labs-examples/system-programms/lab-2/csv-data/people.csv\nt3 = r\nt4 = fopen(t2, t3)\nf = t4\nt6 = opened\nt7 = puts(t6)\nt8 = fgetc(f)\nc = t8\nt10 = read one char\nt11 = puts(t10)\nt12 = fclose(f)\nt13 = done\nt14 = puts(t13)\nt15 = 0\nreturn t15"]
