graph TD;
N0["function: csv_field"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: i"]
N5 --> N6
N7["="]
N4 --> N7
N8["expr"]
N4 --> N8
N9["literal"]
N8 --> N9
N10["dec: 0"]
N9 --> N10
N11[";"]
N2 --> N11
N12["statement"]
N0 --> N12
N13["loop_statement"]
N12 --> N13
N14["while"]
N13 --> N14
N15["expr"]
N13 --> N15
N16["literal"]
N15 --> N16
N17["dec: 1"]
N16 --> N17
N18["statement"]
N13 --> N18
N19["expression_statement"]
N18 --> N19
N20["expr"]
N19 --> N20
N21["binary_expr"]
N20 --> N21
N22["expr"]
N21 --> N22
N23["identifier: c"]
N22 --> N23
N24["="]
N21 --> N24
N25["expr"]
N21 --> N25
N26["call_expr"]
N25 --> N26
N27["expr"]
N26 --> N27
N28["identifier: str_get_byte"]
N27 --> N28
N29["expr"]
N26 --> N29
N30["identifier: line"]
N29 --> N30
N31["expr"]
N26 --> N31
N32["binary_expr"]
N31 --> N32
N33["expr"]
N32 --> N33
N34["identifier: pos"]
N33 --> N34
N35["+"]
N32 --> N35
N36["expr"]
N32 --> N36
N37["identifier: i"]
N36 --> N37
N38[";"]
N19 --> N38
N39["statement"]
N13 --> N39
N40["if_statement"]
N39 --> N40
N41["if"]
N40 --> N41
N42["expr"]
N40 --> N42
N43["binary_expr"]
N42 --> N43
N44["expr"]
N43 --> N44
N45["identifier: c"]
N44 --> N45
N46["=="]
N43 --> N46
N47["expr"]
N43 --> N47
N48["literal"]
N47 --> N48
N49["dec: 0"]
N48 --> N49
N50["statement"]
N40 --> N50
N51["block_statement"]
N50 --> N51
N52["begin"]
N51 --> N52
N53["statement"]
N51 --> N53
N54["expression_statement"]
N53 --> N54
N55["expr"]
N54 --> N55
N56["call_expr"]
N55 --> N56
N57["expr"]
N56 --> N57
N58["identifier: str_set_byte"]
N57 --> N58
N59["expr"]
N56 --> N59
N60["identifier: dst"]
N59 --> N60
N61["expr"]
N56 --> N61
N62["identifier: i"]
N61 --> N62
N63["expr"]
N56 --> N63
N64["literal"]
N63 --> N64
N65["dec: 0"]
N64 --> N65
N66[";"]
N54 --> N66
N67["statement"]
N51 --> N67
N68["return_statement"]
N67 --> N68
N69["expr"]
N68 --> N69
N70["binary_expr"]
N69 --> N70
N71["expr"]
N70 --> N71
N72["identifier: pos"]
N71 --> N72
N73["+"]
N70 --> N73
N74["expr"]
N70 --> N74
N75["identifier: i"]
N74 --> N75
N76["end"]
N51 --> N76
N77["statement"]
N13 --> N77
N78["if_statement"]
N77 --> N78
N79["if"]
N78 --> N79
N80["expr"]
N78 --> N80
N81["binary_expr"]
N80 --> N81
N82["expr"]
N81 --> N82
N83["identifier: c"]
N82 --> N83
N84["=="]
N81 --> N84
N85["expr"]
N81 --> N85
N86["literal"]
N85 --> N86
N87["char: ,"]
N86 --> N87
N88["statement"]
N78 --> N88
N89["block_statement"]
N88 --> N89
N90["begin"]
N89 --> N90
N91["statement"]
N89 --> N91
N92["expression_statement"]
N91 --> N92
N93["expr"]
N92 --> N93
N94["call_expr"]
N93 --> N94
N95["expr"]
N94 --> N95
N96["identifier: str_set_byte"]
N95 --> N96
N97["expr"]
N94 --> N97
N98["identifier: dst"]
N97 --> N98
N99["expr"]
N94 --> N99
N100["identifier: i"]
N99 --> N100
N101["expr"]
N94 --> N101
N102["literal"]
N101 --> N102
N103["dec: 0"]
N102 --> N103
N104[";"]
N92 --> N104
N105["statement"]
N89 --> N105
N106["return_statement"]
N105 --> N106
N107["expr"]
N106 --> N107
N108["binary_expr"]
N107 --> N108
N109["expr"]
N108 --> N109
N110["binary_expr"]
N109 --> N110
N111["expr"]
N110 --> N111
N112["identifier: pos"]
N111 --> N112
N113["+"]
N110 --> N113
N114["expr"]
N110 --> N114
N115["identifier: i"]
N114 --> N115
N116["+"]
N108 --> N116
N117["expr"]
N108 --> N117
N118["literal"]
N117 --> N118
N119["dec: 1"]
N118 --> N119
N120["end"]
N89 --> N120
N121["statement"]
N13 --> N121
N122["expression_statement"]
N121 --> N122
N123["expr"]
N122 --> N123
N124["call_expr"]
N123 --> N124
N125["expr"]
N124 --> N125
N126["identifier: str_set_byte"]
N125 --> N126
N127["expr"]
N124 --> N127
N128["identifier: dst"]
N127 --> N128
N129["expr"]
N124 --> N129
N130["identifier: i"]
N129 --> N130
N131["expr"]
N124 --> N131
N132["identifier: c"]
N131 --> N132
N133[";"]
N122 --> N133
N134["statement"]
N13 --> N134
N135["expression_statement"]
N134 --> N135
N136["expr"]
N135 --> N136
N137["binary_expr"]
N136 --> N137
N138["expr"]
N137 --> N138
N139["identifier: i"]
N138 --> N139
N140["="]
N137 --> N140
N141["expr"]
N137 --> N141
N142["binary_expr"]
N141 --> N142
N143["expr"]
N142 --> N143
N144["identifier: i"]
N143 --> N144
N145["+"]
N142 --> N145
N146["expr"]
N142 --> N146
N147["literal"]
N146 --> N147
N148["dec: 1"]
N147 --> N148
N149[";"]
N135 --> N149
N150["end"]
N13 --> N150
