graph TD
    BB_0["BB0\nt344 = r\nt345 = fopen(fn, t344)\nf = t345\nt346 = 0\nt347 = (f == t346)\nif t347 goto BB_2 else BB_1"]
    BB_2["BB2\nt348 = 1\nt349 = -t348\nreturn t349"]
    BB_3["BB3\nt357 = true\nif t357 goto BB_4 else BB_5"]
    BB_7["BB7\ngoto BB_5"]
    BB_4["BB4\nt358 = read_line(f)\nt359 = 1\nt360 = -t359\nt361 = (t358 == t360)\nif t361 goto BB_7 else BB_6"]
    BB_6["BB6\nt362 = parse_row()\nt363 = sd_n\[?\]\nt364 = sd_pid\[t363\]\nt365 = row_buf\[?\]\nt366 = 0\nt367 = co\[t366\]\nt368 = t365 + t367\nt369 = atoi(t368)\nt370 = sd_n\[?\]\nsd_pid\[0\] = ?\nt371 = sd_n\[?\]\nt372 = sd_group\[t371\]\nt373 = sd_n\[?\]\nsd_group\[0\] = ?\nt374 = sd_buf\[?\]\nt375 = 1\nt376 = co\[t375\]\nt377 = str_save(t374, pos, t376)\npos = t377\nt378 = sd_n\[?\]\nt379 = sd_start\[t378\]\nt380 = sd_n\[?\]\nsd_start\[0\] = ?\nt381 = sd_buf\[?\]\nt382 = 2\nt383 = co\[t382\]\nt384 = str_save(t381, pos, t383)\npos = t384\nt385 = sd_n\[?\]\nt386 = sd_n\[?\]\nt387 = 1\nt388 = t386 + t387\nsd_n = t388\ngoto BB_3"]
    BB_1["BB1\nt350 = read_line(f)\nt351 = sd_n\[?\]\nt352 = 0\nsd_n = t352\nt353 = sd_buf\[?\]\nt354 = 5000\nt355 = malloc(t354)\nsd_buf = t355\nt356 = 0\npos = t356\ngoto BB_3"]
    BB_5["BB5\nt389 = fclose(f)\nt390 = sd_n\[?\]\nreturn t390"]
BB_0 --> BB_2
BB_0 --> BB_1
BB_2 --> BB_1
BB_3 --> BB_4
BB_3 --> BB_5
BB_7 --> BB_5
BB_7 --> BB_6
BB_4 --> BB_7
BB_4 --> BB_6
BB_6 --> BB_3
BB_1 --> BB_3
