graph TD;
N0["function: p_init"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["binary_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["field_access .head"]
N5 --> N6
N7["expr"]
N6 --> N7
N8["identifier: p"]
N7 --> N8
N9["="]
N4 --> N9
N10["expr"]
N4 --> N10
N11["literal"]
N10 --> N11
N12["dec: 0"]
N11 --> N12
N13[";"]
N2 --> N13
N14["statement"]
N0 --> N14
N15["expression_statement"]
N14 --> N15
N16["expr"]
N15 --> N16
N17["binary_expr"]
N16 --> N17
N18["expr"]
N17 --> N18
N19["field_access .tail"]
N18 --> N19
N20["expr"]
N19 --> N20
N21["identifier: p"]
N20 --> N21
N22["="]
N17 --> N22
N23["expr"]
N17 --> N23
N24["literal"]
N23 --> N24
N25["dec: 0"]
N24 --> N25
N26[";"]
N15 --> N26
N27["statement"]
N0 --> N27
N28["expression_statement"]
N27 --> N28
N29["expr"]
N28 --> N29
N30["binary_expr"]
N29 --> N30
N31["expr"]
N30 --> N31
N32["field_access .count"]
N31 --> N32
N33["expr"]
N32 --> N33
N34["identifier: p"]
N33 --> N34
N35["="]
N30 --> N35
N36["expr"]
N30 --> N36
N37["literal"]
N36 --> N37
N38["dec: 0"]
N37 --> N38
N39[";"]
N28 --> N39
