graph TD
    BB_0["BB0\nt560 = === Q3: Count FCE without patronymic ===\nt561 = puts(t560)\nt562 = 0\ncount = t562\nt563 = 0\ni = t563\ngoto BB_1"]
    BB_1["BB1\nt564 = pp_n\[?\]\nt565 = (i < t564)\nif t565 goto BB_2 else BB_3"]
    BB_6["BB6\nt572 = st_n\[?\]\nt573 = (si < t572)\nif t573 goto BB_7 else BB_8"]
    BB_11["BB11\nt585 = sd_n\[?\]\nt586 = (di < t585)\nif t586 goto BB_12 else BB_13"]
    BB_15["BB15\nt590 = 1\nt591 = count + t590\ncount = t591\ngoto BB_13"]
    BB_12["BB12\nt587 = sd_pid\[di\]\nt588 = pp_id\[i\]\nt589 = (t587 == t588)\nif t589 goto BB_15 else BB_14"]
    BB_14["BB14\nt592 = 1\nt593 = di + t592\ndi = t593\ngoto BB_11"]
    BB_10["BB10\nt584 = 0\ndi = t584\ngoto BB_11"]
    BB_13["BB13\ngoto BB_8"]
    BB_7["BB7\nt574 = st_pid\[si\]\nt575 = pp_id\[i\]\nt576 = (t574 == t575)\nt577 = st_buf\[?\]\nt578 = st_fac\[si\]\nt579 = FCE\nt580 = str_eq_lit(t577, t578, t579)\nt581 = 0\nt582 = (t580 != t581)\nt583 = t576 && t582\nif t583 goto BB_10 else BB_9"]
    BB_9["BB9\nt594 = 1\nt595 = si + t594\nsi = t595\ngoto BB_6"]
    BB_5["BB5\nt571 = 0\nsi = t571\ngoto BB_6"]
    BB_8["BB8\ngoto BB_4"]
    BB_2["BB2\nt566 = pp_buf\[?\]\nt567 = pp_patr\[i\]\nt568 = str_empty(t566, t567)\nt569 = 0\nt570 = (t568 != t569)\nif t570 goto BB_5 else BB_4"]
    BB_4["BB4\nt596 = 1\nt597 = i + t596\ni = t597\ngoto BB_1"]
    BB_3["BB3\nt598 = %d\\n\nt599 = printf(t598, count)\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_6 --> BB_7
BB_6 --> BB_8
BB_11 --> BB_12
BB_11 --> BB_13
BB_15 --> BB_13
BB_15 --> BB_14
BB_12 --> BB_15
BB_12 --> BB_14
BB_14 --> BB_11
BB_10 --> BB_11
BB_13 --> BB_8
BB_13 --> BB_9
BB_7 --> BB_10
BB_7 --> BB_9
BB_9 --> BB_6
BB_5 --> BB_6
BB_8 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_4 --> BB_1
