graph TD
    BB_0["BB0\nt682 = === Q5: Avg grades 4100 >= 1100 ===\nt683 = puts(t682)\nt684 = 1100\nt685 = group_avg(t684)\navg1100 = t685\nt686 = Avg 1100 = %d\\n\nt687 = printf(t686, avg1100)\nt688 = 0\nfound = t688\nt689 = 0\ni = t689\ngoto BB_1"]
    BB_1["BB1\nt690 = sd_n\[?\]\nt691 = (i < t690)\nif t691 goto BB_2 else BB_3"]
    BB_6["BB6\nt702 = vv_n\[?\]\nt703 = (j < t702)\nif t703 goto BB_7 else BB_8"]
    BB_10["BB10\nt710 = vv_mark\[j\]\nt711 = sum + t710\nsum = t711\nt712 = 1\nt713 = cnt + t712\ncnt = t713\ngoto BB_9"]
    BB_7["BB7\nt704 = vv_pid\[j\]\nt705 = (t704 == pid)\nt706 = vv_mark\[j\]\nt707 = 3\nt708 = (t706 >= t707)\nt709 = t705 && t708\nif t709 goto BB_10 else BB_9"]
    BB_9["BB9\nt714 = 1\nt715 = j + t714\nj = t715\ngoto BB_6"]
    BB_5["BB5\nt698 = sd_pid\[i\]\npid = t698\nt699 = 0\nsum = t699\nt700 = 0\ncnt = t700\nt701 = 0\nj = t701\ngoto BB_6"]
    BB_15["BB15\nt723 = pp_n\[?\]\nt724 = (pi < t723)\nif t724 goto BB_16 else BB_17"]
    BB_19["BB19\nt727 = %d\nt728 = printf(t727, pid)\nt729 = 44\nt730 = putchar(t729)\nt731 = 32\nt732 = putchar(t731)\nt733 = pp_buf\[?\]\nt734 = pp_surname\[pi\]\n? = print_str(t733, t734)\nt735 = 32\nt736 = putchar(t735)\nt737 = pp_buf\[?\]\nt738 = pp_name\[pi\]\n? = print_str(t737, t738)\nt739 =  %d.%d\\n\nt740 = 10\nt741 = pavg / t740\nt742 = 10\nt743 = pavg % t742\nt744 = printf(t739, t741, t743)\nt745 = 1\nt746 = found + t745\nfound = t746\ngoto BB_18"]
    BB_16["BB16\nt725 = pp_id\[pi\]\nt726 = (t725 == pid)\nif t726 goto BB_19 else BB_18"]
    BB_18["BB18\nt747 = 1\nt748 = pi + t747\npi = t748\ngoto BB_15"]
    BB_14["BB14\nt722 = 0\npi = t722\ngoto BB_15"]
    BB_17["BB17\ngoto BB_13"]
    BB_12["BB12\nt718 = 10\nt719 = sum * t718\nt720 = t719 / cnt\npavg = t720\nt721 = (pavg >= avg1100)\nif t721 goto BB_14 else BB_13"]
    BB_13["BB13\ngoto BB_11"]
    BB_8["BB8\nt716 = 0\nt717 = (cnt != t716)\nif t717 goto BB_12 else BB_11"]
    BB_11["BB11\ngoto BB_4"]
    BB_2["BB2\nt692 = sd_buf\[?\]\nt693 = sd_group\[i\]\nt694 = 4100\nt695 = str_eq_lit(t692, t693, t694)\nt696 = 0\nt697 = (t695 != t696)\nif t697 goto BB_5 else BB_4"]
    BB_4["BB4\nt749 = 1\nt750 = i + t749\ni = t750\ngoto BB_1"]
    BB_3["BB3\nt751 = Found: %d\\n\nt752 = printf(t751, found)\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_6 --> BB_7
BB_6 --> BB_8
BB_10 --> BB_9
BB_7 --> BB_10
BB_7 --> BB_9
BB_9 --> BB_6
BB_5 --> BB_6
BB_15 --> BB_16
BB_15 --> BB_17
BB_19 --> BB_18
BB_16 --> BB_19
BB_16 --> BB_18
BB_18 --> BB_15
BB_14 --> BB_15
BB_17 --> BB_13
BB_12 --> BB_14
BB_12 --> BB_13
BB_13 --> BB_11
BB_8 --> BB_12
BB_8 --> BB_11
BB_11 --> BB_4
BB_2 --> BB_5
BB_2 --> BB_4
BB_4 --> BB_1
