graph TD
    BB_0["BB0\nt817 = === Q7: Same surname, diff bday ===\nt818 = puts(t817)\nt819 = 0\ni = t819\ngoto BB_1"]
    BB_1["BB1\nt820 = 100\nt821 = (i < t820)\nif t821 goto BB_2 else BB_3"]
    BB_2["BB2\nt822 = w\[i\]\nt823 = 0\nw\[0\] = ?\nt824 = 1\nt825 = i + t824\ni = t825\ngoto BB_1"]
    BB_4["BB4\nt827 = pp_n\[?\]\nt828 = (i < t827)\nif t828 goto BB_5 else BB_6"]
    BB_7["BB7\nt831 = pp_n\[?\]\nt832 = (j < t831)\nif t832 goto BB_8 else BB_9"]
    BB_13["BB13\nt845 = w\[i\]\nt846 = 1\nw\[0\] = ?\nt847 = w\[j\]\nt848 = 1\nw\[0\] = ?\ngoto BB_12"]
    BB_11["BB11\nt839 = pp_buf\[?\]\nt840 = pp_bday\[i\]\nt841 = pp_bday\[j\]\nt842 = str_eq(t839, t840, t841)\nt843 = 0\nt844 = (t842 == t843)\nif t844 goto BB_13 else BB_12"]
    BB_12["BB12\ngoto BB_10"]
    BB_8["BB8\nt833 = pp_buf\[?\]\nt834 = pp_surname\[i\]\nt835 = pp_surname\[j\]\nt836 = str_eq(t833, t834, t835)\nt837 = 0\nt838 = (t836 != t837)\nif t838 goto BB_11 else BB_10"]
    BB_10["BB10\nt849 = 1\nt850 = j + t849\nj = t850\ngoto BB_7"]
    BB_5["BB5\nt829 = 1\nt830 = i + t829\nj = t830\ngoto BB_7"]
    BB_9["BB9\nt851 = 1\nt852 = i + t851\ni = t852\ngoto BB_4"]
    BB_3["BB3\nt826 = 0\ni = t826\ngoto BB_4"]
    BB_14["BB14\nt855 = pp_n\[?\]\nt856 = (i < t855)\nif t856 goto BB_15 else BB_16"]
    BB_18["BB18\nt860 = pp_buf\[?\]\nt861 = pp_surname\[i\]\n? = print_str(t860, t861)\nt862 = 44\nt863 = putchar(t862)\nt864 = 32\nt865 = putchar(t864)\nt866 = pp_buf\[?\]\nt867 = pp_name\[i\]\n? = print_str(t866, t867)\nt868 = 44\nt869 = putchar(t868)\nt870 = 32\nt871 = putchar(t870)\nt872 = pp_buf\[?\]\nt873 = pp_bday\[i\]\n? = print_str(t872, t873)\nt874 = 10\nt875 = putchar(t874)\nt876 = 1\nt877 = count + t876\ncount = t877\ngoto BB_17"]
    BB_15["BB15\nt857 = w\[i\]\nt858 = 0\nt859 = (t857 != t858)\nif t859 goto BB_18 else BB_17"]
    BB_17["BB17\nt878 = 1\nt879 = i + t878\ni = t879\ngoto BB_14"]
    BB_6["BB6\nt853 = 0\ncount = t853\nt854 = 0\ni = t854\ngoto BB_14"]
    BB_16["BB16\nt880 = Groups: %d\\n\nt881 = printf(t880, count)\nreturn"]
BB_0 --> BB_1
BB_1 --> BB_2
BB_1 --> BB_3
BB_2 --> BB_1
BB_4 --> BB_5
BB_4 --> BB_6
BB_7 --> BB_8
BB_7 --> BB_9
BB_13 --> BB_12
BB_11 --> BB_13
BB_11 --> BB_12
BB_12 --> BB_10
BB_8 --> BB_11
BB_8 --> BB_10
BB_10 --> BB_7
BB_5 --> BB_7
BB_9 --> BB_4
BB_3 --> BB_4
BB_14 --> BB_15
BB_14 --> BB_16
BB_18 --> BB_17
BB_15 --> BB_18
BB_15 --> BB_17
BB_17 --> BB_14
BB_6 --> BB_14
