graph TD;
N0["source"]
N1["source_item"]
N0 --> N1
N2["def"]
N1 --> N2
N3["func_signature"]
N1 --> N3
N4["identifier: main"]
N3 --> N4
N5["("]
N3 --> N5
N6[")"]
N3 --> N6
N7["statement"]
N1 --> N7
N8["if_statement"]
N7 --> N8
N9["if"]
N8 --> N9
N10["expr"]
N8 --> N10
N11["expr"]
N10 --> N11
N12["literal"]
N11 --> N12
N13["dec: 5"]
N12 --> N13
N14["then"]
N8 --> N14
N15["statement"]
N8 --> N15
N16["expression_statement"]
N15 --> N16
N17["expr"]
N16 --> N17
N18["binary_expr"]
N17 --> N18
N19["expr"]
N17 --> N19
N20["expr"]
N19 --> N20
N21["identifier: i"]
N20 --> N21
N22["="]
N17 --> N22
N23["expr"]
N17 --> N23
N24["expr"]
N23 --> N24
N25["literal"]
N24 --> N25
N26["dec: 1"]
N25 --> N26
N27[";"]
N16 --> N27
N28["end"]
N8 --> N28
N29["end"]
N1 --> N29
