graph TD;
N0["function: main"]
N1["statement"]
N0 --> N1
N2["expression_statement"]
N1 --> N2
N3["expr"]
N2 --> N3
N4["call_expr"]
N3 --> N4
N5["expr"]
N4 --> N5
N6["identifier: puts"]
N5 --> N6
N7["expr"]
N4 --> N7
N8["literal"]
N7 --> N8
N9["str: "open""]
N8 --> N9
N10[";"]
N2 --> N10
N11["statement"]
N0 --> N11
N12["expression_statement"]
N11 --> N12
N13["expr"]
N12 --> N13
N14["binary_expr"]
N13 --> N14
N15["expr"]
N14 --> N15
N16["identifier: f"]
N15 --> N16
N17["="]
N14 --> N17
N18["expr"]
N14 --> N18
N19["call_expr"]
N18 --> N19
N20["expr"]
N19 --> N20
N21["identifier: fopen"]
N20 --> N21
N22["expr"]
N19 --> N22
N23["literal"]
N22 --> N23
N24["str: "labs-examples/system-programms/lab-2/csv-data/people.csv""]
N23 --> N24
N25["expr"]
N19 --> N25
N26["literal"]
N25 --> N26
N27["str: "r""]
N26 --> N27
N28[";"]
N12 --> N28
N29["statement"]
N0 --> N29
N30["if_statement"]
N29 --> N30
N31["if"]
N30 --> N31
N32["expr"]
N30 --> N32
N33["binary_expr"]
N32 --> N33
N34["expr"]
N33 --> N34
N35["identifier: f"]
N34 --> N35
N36["=="]
N33 --> N36
N37["expr"]
N33 --> N37
N38["literal"]
N37 --> N38
N39["str: """]
N38 --> N39
N40["statement"]
N30 --> N40
N41["expression_statement"]
N40 --> N41
N42["expr"]
N41 --> N42
N43["call_expr"]
N42 --> N43
N44["expr"]
N43 --> N44
N45["identifier: puts"]
N44 --> N45
N46["expr"]
N43 --> N46
N47["literal"]
N46 --> N47
N48["str: "FAIL""]
N47 --> N48
N49[";"]
N41 --> N49
N50["statement"]
N30 --> N50
N51["expression_statement"]
N50 --> N51
N52["expr"]
N51 --> N52
N53["call_expr"]
N52 --> N53
N54["expr"]
N53 --> N54
N55["identifier: puts"]
N54 --> N55
N56["expr"]
N53 --> N56
N57["literal"]
N56 --> N57
N58["str: "OK""]
N57 --> N58
N59[";"]
N51 --> N59
N60["statement"]
N0 --> N60
N61["if_statement"]
N60 --> N61
N62["if"]
N61 --> N62
N63["expr"]
N61 --> N63
N64["binary_expr"]
N63 --> N64
N65["expr"]
N64 --> N65
N66["identifier: f"]
N65 --> N66
N67["!="]
N64 --> N67
N68["expr"]
N64 --> N68
N69["literal"]
N68 --> N69
N70["str: """]
N69 --> N70
N71["statement"]
N61 --> N71
N72["expression_statement"]
N71 --> N72
N73["expr"]
N72 --> N73
N74["call_expr"]
N73 --> N74
N75["expr"]
N74 --> N75
N76["identifier: fgets"]
N75 --> N76
N77["expr"]
N74 --> N77
N78["identifier: buf"]
N77 --> N78
N79["expr"]
N74 --> N79
N80["literal"]
N79 --> N80
N81["dec: 256"]
N80 --> N81
N82["expr"]
N74 --> N82
N83["identifier: f"]
N82 --> N83
N84[";"]
N72 --> N84
N85["statement"]
N0 --> N85
N86["expression_statement"]
N85 --> N86
N87["expr"]
N86 --> N87
N88["call_expr"]
N87 --> N88
N89["expr"]
N88 --> N89
N90["identifier: puts"]
N89 --> N90
N91["expr"]
N88 --> N91
N92["identifier: buf"]
N91 --> N92
N93[";"]
N86 --> N93
N94["statement"]
N0 --> N94
N95["expression_statement"]
N94 --> N95
N96["expr"]
N95 --> N96
N97["call_expr"]
N96 --> N97
N98["expr"]
N97 --> N98
N99["identifier: fgets"]
N98 --> N99
N100["expr"]
N97 --> N100
N101["identifier: buf"]
N100 --> N101
N102["expr"]
N97 --> N102
N103["literal"]
N102 --> N103
N104["dec: 256"]
N103 --> N104
N105["expr"]
N97 --> N105
N106["identifier: f"]
N105 --> N106
N107[";"]
N95 --> N107
N108["statement"]
N0 --> N108
N109["expression_statement"]
N108 --> N109
N110["expr"]
N109 --> N110
N111["call_expr"]
N110 --> N111
N112["expr"]
N111 --> N112
N113["identifier: puts"]
N112 --> N113
N114["expr"]
N111 --> N114
N115["identifier: buf"]
N114 --> N115
N116[";"]
N109 --> N116
N117["statement"]
N0 --> N117
N118["expression_statement"]
N117 --> N118
N119["expr"]
N118 --> N119
N120["call_expr"]
N119 --> N120
N121["expr"]
N120 --> N121
N122["identifier: fclose"]
N121 --> N122
N123["expr"]
N120 --> N123
N124["identifier: f"]
N123 --> N124
N125[";"]
N118 --> N125
