graph TD
    BB_6["BB6\nt17 = buf\[?\]\nt18 = puts(t17)\nt19 = buf\[?\]\nt20 = 256\nt21 = fgets(t19, t20, f)\nt22 = buf\[?\]\nt23 = puts(t22)\nt24 = fclose(f)"]
    BB_1["BB1\nt8 = FAIL\nt9 = puts(t8)\ngoto BB_3"]
    BB_2["BB2\nt10 = OK\nt11 = puts(t10)\ngoto BB_3"]
    BB_0["BB0\nt0 = open\nt1 = puts(t0)\nt2 = labs-examples/system-programms/lab-2/csv-data/people.csv\nt3 = r\nt4 = fopen(t2, t3)\nf = t4\nt6 = \nt7 = (f == t6)\nif t7 goto BB_1 else BB_2"]
    BB_4["BB4\nt14 = buf\[?\]\nt15 = 256\nt16 = fgets(t14, t15, f)\ngoto BB_6"]
    BB_5["BB5\ngoto BB_6"]
    BB_3["BB3\nt12 = \nt13 = (f != t12)\nif t13 goto BB_4 else BB_5"]
BB_1 --> BB_3
BB_2 --> BB_3
BB_0 --> BB_1
BB_0 --> BB_2
BB_4 --> BB_6
BB_5 --> BB_6
BB_3 --> BB_4
BB_3 --> BB_5
